### ISSUE TITLE
Error Loading Localization Language on Startup

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#1]
**Describe the bug**
After compiling the project! it appears to miss the localsize file / or resource

**To Reproduce**
Just load the project it will appears on start up the project

**Screenshots**
![image](https://user-images.githubusercontent.com/31751665/109592542-006af680-7b42-11eb-8f30-8e04f31da582.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by iammukeshm** [comment]
Fixed.
