### ISSUE TITLE
Could you consider  adding an approval process sample？

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#100]
A common approval workflow applies to many business scenarios, such as a form submission  that requires someone to approve it, approved or rejected

**Comment by iang0ld** [comment]
You may want to check this out.
https://sipkeschoorstra.medium.com/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50

From: neozhu ***@***.***>
Sent: Friday, 14 May 2021 9:50 AM
To: blazorhero/CleanArchitecture ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blazorhero/CleanArchitecture] Could you consider adding an approval process sample？ (#100)


A common approval workflow applies to many business scenarios, such as a form submission that requires someone to approve it, approved or rejected

**Comment by neozhu** [comment]
thank you for your information. But I still don't know how to use ELAS in web project or Blazor web application

**Comment by nbiada** [comment]
https://github.com/danielgerlag/workflow-core

**Comment by neozhu** [comment]
@nbiada workflow-core is a great project too, I've been attending it for a long time. 
could you make a simple demo page?

**Comment by nbiada** [comment]
@neozhu yes, for sure.
Submission -> Request of Approval -> Approved / Rejected.
Ok ?

**Comment by neozhu** [comment]
Yes, I don't understand how to implement a human approval workflow？ Submit a form(like one document) -> waiting to approve -> approved/rejected -> completed.
e.g.
add document record - status:draft -> action:submit -> status:wait approve(send mail to appover) -> action:approved(status: approved)
