### ISSUE TITLE
Add Prerender support to improve initial user experience

### ISSUE THREAD

**Issue by jasonabanico** [fullstackhero/blazor-starter-kit#101]
Adding prerender support will make it more user-friendly, not requiring the user to wait for download to begin interacting with the app.

I am trying it to add prerendering myself, but there are so many services that need to be set up and implement on the server-side. I also am not familiar with what all the services do.

**Comment by unchase** [comment]
Hi, @jasebanico 
How did you add prerender to yourself? Can you show the code example?

**Comment by jasonabanico** [comment]
Hi. This is my attempt at doing it, but didn't get to finish, as there's too many services to migrate and I need to learn what each one does.

https://github.com/jasebanico/BlazorWorld2/commit/035ac01f1b520163cbcfa24e0e1da72f2e21819e

I'm following this article:
https://andrewlock.net/enabling-prerendering-for-blazor-webassembly-apps/

**Comment by neozhu** [comment]
@jasebanico 
I just tried to refactor the code, but it's failed, 
Can you share your code?

**Comment by jasonabanico** [comment]
Hi @neozhu . My attempt to do it is found here:
https://github.com/jasebanico/BlazorWorld2/commit/035ac01f1b520163cbcfa24e0e1da72f2e21819e
