### ISSUE TITLE
how to add new Permissions

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#103]
![image](https://user-images.githubusercontent.com/1549611/118572809-dd042f00-b7b3-11eb-9907-81099748bc16.png)
![image](https://user-images.githubusercontent.com/1549611/118572878-ff964800-b7b3-11eb-9883-ca35639039d5.png)
![image](https://user-images.githubusercontent.com/1549611/118573264-c6aaa300-b7b4-11eb-90ca-c241d039696c.png)
![image](https://user-images.githubusercontent.com/1549611/118572972-2c4a5f80-b7b4-11eb-8d94-9890ec49bf1c.png)
configuration user,role,permissions is correct.
why _authorizationService.AuthorizeAsync(AuthenticationStateProviderUser, Permissions.Roles.View) is not available?

**Comment by chhinsras** [comment]
I can see our Permission.Products.View  2 records.

delete one. it will solve.

**Comment by neozhu** [comment]
> I can see our Permission.Products.View 2 records.
> 
> delete one. it will solve.
![image](https://user-images.githubusercontent.com/1549611/118578771-56ede580-b7bf-11eb-9e2c-fbaeb73ce0b3.png)
It belongs to two different roles, "administrator", "Basic" ， isn't right?

**Comment by chhinsras** [comment]
this is true. need to check it. maybe we can work together to see.

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/118579711-2c049100-b7c1-11eb-84ef-a38e10b0a4b6.png)

was the issue here? not add role information to AuthenticationState

**Comment by chhinsras** [comment]
You can check on the console log. what has happened

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/118579711-2c049100-b7c1-11eb-84ef-a38e10b0a4b6.png)

was the issue here? not add role information to AuthenticationState;
It's right.I found it.
![image](https://user-images.githubusercontent.com/1549611/118582840-a257c200-b7c6-11eb-89c9-41562c191ffe.png)

but I still not found this issue

**Comment by chhinsras** [comment]
need to check it. maybe later. I can remote to see

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/118584069-b8ff1880-b7c8-11eb-8670-a167f1502f88.png)
I found not execute this code when I debug it.
My debug source code clone from "https://github.com/blazorhero/CleanArchitecture.git"

**Comment by chhinsras** [comment]
then you need to dig into that stateProvider class

**Comment by neozhu** [comment]
I found this issue,
![image](https://user-images.githubusercontent.com/1549611/118585373-56f3e280-b7cb-11eb-9966-cc64b0a69d3d.png)
I create a new permission "Permissions.Companies.View",
![image](https://user-images.githubusercontent.com/1549611/118585587-cbc71c80-b7cb-11eb-84bc-fadea19d8ae2.png)

how to create new permission?

**Comment by chhinsras** [comment]
You can follow how @iammukeshm created for Chat permission.

**Comment by chhinsras** [comment]
or you can follow what I did #44 here.

**Comment by neozhu** [comment]
Here is workable.
RegisgterPermissionClaimPolicyByModule(options, typeof(Permissions.Products));
RegisgterPermissionClaimPolicyByModule(options, typeof(Permissions.Brands));
I can't find the above code?

**Comment by chhinsras** [comment]
` private static void RegisgterPermissionClaimPolicyByModule(AuthorizationOptions options, Type module)
        {
            foreach (var prop in module.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy))
            {
                options.AddPolicy(prop.GetValue(null).ToString(), policy => policy.RequireClaim(ApplicationClaimTypes.Permission, prop.GetValue(null).ToString()));
            }
        }`

**Comment by chhinsras** [comment]
you need to create helper function for this.  this is my linkedin. we can chat https://www.linkedin.com/in/chhin-sras-3924b5119/

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/118593480-59aa0400-b7da-11eb-9f45-2845c2710a79.png)
this is add policy  function.right?

![image](https://user-images.githubusercontent.com/1549611/118593770-d3da8880-b7da-11eb-83da-974dd0d779e1.png)
why not read Permissions properties?

**Comment by neozhu** [comment]
I found  that the following code did not find any available properties at all, so  permissions are not registered
```services.AddAuthorization(options =>
            {
                // Here I stored necessary permissions/roles in a constant
                foreach (var prop in typeof(Permissions).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy))
                {
                    options.AddPolicy(prop.GetValue(null).ToString(), 
                        policy => policy.RequireClaim(ApplicationClaimTypes.Permission, prop.GetValue(null).ToString()));
                }
            });`

**Comment by neozhu** [comment]
thank you a lot. @chhinsras 
I got it.
client registration code is here.
![image](https://user-images.githubusercontent.com/1549611/118603226-3a18d880-b7e6-11eb-9b6c-dd0c68bf07ea.png)
now it's ok.
![image](https://user-images.githubusercontent.com/1549611/118603450-7f3d0a80-b7e6-11eb-924e-f9d7bb722635.png)
so. how to add new permissions :
the first step add define permission name :
![image](https://user-images.githubusercontent.com/1549611/118603724-dc38c080-b7e6-11eb-8f2f-86e752139e0e.png)
the second  step register permission policy By Module
![image](https://user-images.githubusercontent.com/1549611/118604456-c4ae0780-b7e7-11eb-9e47-faecb161401c.png)
the third  step configuration/authorization permission  by role
![image](https://user-images.githubusercontent.com/1549611/118604008-3afe3a00-b7e7-11eb-81d2-8d6507abce81.png)
![image](https://user-images.githubusercontent.com/1549611/118604903-469e3080-b7e8-11eb-901e-878078f5f51b.png)

the end add navigation menu
![image](https://user-images.githubusercontent.com/1549611/118604626-f58e3c80-b7e7-11eb-9312-f0f4435a4771.png)

Thank you again for your helpe.

**Comment by chhinsras** [comment]
Perfect! You are on the right track.
