### ISSUE TITLE
can you  move  the menu button position ？

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#105]
![image](https://user-images.githubusercontent.com/1549611/118626515-84f21a80-b7fd-11eb-8b52-3aa4e8752e0c.png)

**Comment by Duelbat** [comment]
Yes please.  +1

**Comment by amitpercept** [comment]
In MainLayout.razor File move **MudToolBar** from MudMainContent to just below MudText "Blazor Hero"

![BlazorHeroMenuDrawer](https://user-images.githubusercontent.com/46813942/119497950-be3d0400-bd82-11eb-946b-05b14229b8b5.png)

Hope it helps!

**Comment by neozhu** [comment]
> In MainLayout.razor File move **MudToolBar** from MudMainContent to just below MudText "Blazor Hero"
> 
> ![BlazorHeroMenuDrawer](https://user-images.githubusercontent.com/46813942/119497950-be3d0400-bd82-11eb-946b-05b14229b8b5.png)
> 
> Hope it helps!

it's great. thank you
