### ISSUE TITLE
How we can protect Endpoint using role permissions?

### ISSUE THREAD

**Issue by sahvey** [fullstackhero/blazor-starter-kit#11]
The following endpoint is unprotected since [Authorize] attribute is not used.
How can we protect below endpoint using role permissions rather than roles?

```
 BlazorHero.CleanArchitecture.Server.Controllers.v1.Catalog
{
    public class ProductsController : BaseApiController<ProductsController>
    {
        [HttpGet]
        public async Task<IActionResult> GetAll.......
        .
        .
    }
}
```
How can I protect this endpoint by adding the [Authorize (Policy = "Products.View")] attribute to Jwt. 
How can I verify role permissions after I have protected them.

You have always used permissions on the UI side in this project and other projects, but you never used permissions on the Api side.

It will be very nice if you use an example on the api side in this project.

**Comment by iammukeshm** [comment]
Hi, It is already on the way. The code will be commited in a while :)
