### ISSUE TITLE
Right to left direction option and jalali date

### ISSUE THREAD

**Issue by mammadkoma** [fullstackhero/blazor-starter-kit#115]
Hello
Does this project have rtl direction option and jalali (persian) date picker?

**Comment by unchase** [comment]
Hi, @mammadkoma 
Should to add persian localization for using jalali (persian) date picker.

**Comment by iammukeshm** [comment]
RTL will be added soon to this project. Probably in the next few updates.

**Comment by iammukeshm** [comment]
Done.

**Comment by mammadkoma** [comment]
Thanks
