### ISSUE TITLE
Broken Style for Version 2.1

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#117]
![image](https://user-images.githubusercontent.com/31751665/119245563-752f5900-bba4-11eb-9499-1666f57e5b3f.png)

![image](https://user-images.githubusercontent.com/31751665/119245573-85473880-bba4-11eb-8b51-5d0013e4788e.png)

![image](https://user-images.githubusercontent.com/31751665/119245589-b3c51380-bba4-11eb-9674-fdc83255d113.png)

![image](https://user-images.githubusercontent.com/31751665/119245606-d48d6900-bba4-11eb-9e3a-2f6a384babde.png)

**Comment by supermun** [comment]
Clear all your browsing data / change browser will fix it.
