### ISSUE TITLE
Mudblazor Overflow Table is not responsive

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#118]
This is getting from users table. when there are many columns. on mobile view this is not responsive.

![image](https://user-images.githubusercontent.com/31751665/119245658-259d5d00-bba5-11eb-8299-0d6caf76f027.png)

**Comment by amitpercept** [comment]
Upgrading MudBlazor to latest Version resolved this problem.

**Comment by unchase** [comment]
Related to https://github.com/Garderoben/MudBlazor/issues/1560
