### ISSUE TITLE
is this going to work only in wasm mode, can we get server side version?

### ISSUE THREAD

**Issue by swiftinitdotcom** [fullstackhero/blazor-starter-kit#119]
This is great!
is this going to work only in wasm mode, can we get server side version?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iammukeshm** [comment]
Switching from WASM to Server mode should be possible in the upcoming releases.

**Comment by swiftinitdotcom** [comment]
This is great! Do you tentatively know when this will happen, I mean we have one project starting in few weeks time, wanted to see if this can be used as base. Thank you.
