### ISSUE TITLE
v2.1.0 release failed to build in VS2019

### ISSUE THREAD

**Issue by bernardphua** [fullstackhero/blazor-starter-kit#120]
After getting the latest release 2.1.0 from GitHub, the BlazorHero CleanArchitecture failed to build in VS2019 on Windows 10. I'm getting below error when building the BlazorHero.CleanArchitecture.Application Project. Anyone know how to fix this issue? Thanks.

![image](https://user-images.githubusercontent.com/46226572/119248245-78d1d880-bbc2-11eb-8636-20e95dfa6406.png)

**Comment by iammukeshm** [comment]
where is your project folder located? can I see the entire path?

**Comment by iammukeshm** [comment]
For your understanding, My test application (Blazor Hero) is here - E:\NUGET\BH\SomeApplication\. It builds fine without any exceptions. I suspect that your path where the project lives is too long and windows has a hard time with it. You should probably move your project to a simpler PATH.

**Comment by bernardphua** [comment]
Hi @iammukeshm,

My BlazorHero Application project path is in: C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Application 

Anyway to overcome this long path restriction instead of moving it to C: drive root folder? Thanks!

**Comment by iammukeshm** [comment]
Since this is a more Windows Specific configuration, I wouldn't actually recommend doing it. There is a key in Registry which you might have to enable. Check this ticket - https://stackoverflow.com/questions/8745215/best-way-to-resolve-file-path-too-long-exception

**Comment by chhinsras** [comment]
It is believed to move your project to simplest path as possible. It is just not necessary to move your project into very long folder stacks.
