### ISSUE TITLE
I have a question? how did  implement FluentValidation？

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#123]
I have a question? how did implement FluentValidation？
![image](https://user-images.githubusercontent.com/1549611/119287040-3d91e100-bc78-11eb-9a84-9104c6e98892.png)
 I did not found the register "AddEditProductCommandValidator" code yet,
"service.AddValidatorsFromAssemblyContaining<T>" method I did not found anywhere.
can anybody tell me this point?

**Comment by unchase** [comment]
Hi, @neozhu 

1. Register all Validators in application layer by using `RegisterValidatorsFromAssembly` from `BlazorHero.CleanArchitecture/Server/Extensions/MvcBuilderExtensions.cs` (already used)
2. Add `<FluentValidationValidator @ref="_fluentValidationValidator" />` to the page `.razor`
3. Add `private FluentValidationValidator _fluentValidationValidator;` to the cs-file `.razor.cs`

**Comment by neozhu** [comment]
Thank you for your information.
I got it.

BlazorHero.CleanArchitecture.Client project is not necessary to register the validators, Right?

**Comment by unchase** [comment]
Right, registration occurs through DI in the server project.
