### ISSUE TITLE
Product / Brands Import Feature 

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#126]
Since there is already export functionality implemented.

**Comment by unchase** [comment]
@chhinsras what kind of import do you want? From file or another source?

**Comment by chhinsras** [comment]
@unchase  from excel file . and what else should be adding?

**Comment by unchase** [comment]
* excel (csv, xlsx)
* json
* yaml
* xml

**Comment by chhinsras** [comment]
@unchase , perfect. excel will be most important.

**Comment by neozhu** [comment]
> @unchase , perfect. excel will be most important.
configurable (mapping fields) or configurable templates excel imports?

**Comment by planet-miklos** [comment]
I'm new to BlazorHero and Clean Architecture. Had a go at adding a CSV Loader to Brands.razor

`Brands.razor`
```
<InputFile id="fileInput" OnChange="OnInputFileChange" hidden multiple />
<MudButton HtmlTag="label" Variant="Variant.Filled" Color="Color.Tertiary" StartIcon="@Icons.Filled.CloudUpload" for="fileInput">Upload Files</MudButton>
```

`Brands.razor.cs`

        async Task OnInputFileChange(InputFileChangeEventArgs e)
        {
            foreach (IBrowserFile browserFile in e.GetMultipleFiles())
            {
                IResult<List<GetAllBrandsResponse>> result = await BrandManager.GetAllAsync();
                if (!result.Succeeded)
                {
                    return;
                }
				
                List<GetAllBrandsResponse> allBrands = result.Data;

                IList<BrandCsvResponse> csvBrands = await BrandsCsvReader.OnInputFileChange(browserFile);

                foreach (var csvBrand in csvBrands)
                {
                    int id = 0;
                    _brand = allBrands.FirstOrDefault(c => c.Name == csvBrand.Name);
                    if (_brand != null)
                    {
                        id = _brand.Id;
                    }

                    IResult<int> brandId = await BrandManager.SaveAsync(new AddEditBrandCommand
                    {
                        Id = id,
                        Name = csvBrand.Name,
                        Description = csvBrand.Description,
                        Tax = csvBrand.Tax,
                    });
                }
				
                await GetBrandsAsync();
            }
        }

![image](https://user-images.githubusercontent.com/51025889/194188216-7c27225d-ed3c-46bc-8755-6ea1fad460e9.png)

`BrandCsvResponse.cs`

```
    public class BrandCsvResponse
    {
        [Index(0)]
        public int Id { get; set; }
        [Index(1)]
	public string Name { get; set; }
        [Index(2)]
        public string Description { get; set; }
        [Index(3)]
        public decimal Tax { get; set; }
    }
```

`BrandsCsvReader.cs`

 ```
  public class BrandsCsvReader
    {
        public static async Task<IList<BrandCsvResponse>> OnInputFileChange(IBrowserFile browserFile)
        {
            CsvConfiguration configuration = new(CultureInfo.InvariantCulture)
            {
                Delimiter = ",",
                Comment = '#',
                HasHeaderRecord = true
            };

            var stream = browserFile.OpenReadStream();
            MemoryStream ms = new MemoryStream();
            await stream.CopyToAsync(ms);
            ms.Position = 0;
            stream.Close();

            IList<BrandCsvResponse> _brandList;
            using (var reader = new StreamReader(ms))
            using (var csv = new CsvReader(reader, configuration))
            {
                csv.Context.RegisterClassMap<BrandCsvMap>();
                _brandList = csv.GetRecords<BrandCsvResponse>().ToList();
            }

            return _brandList;
        }
    }
```
	
`BrandCsvMap.cs`

```
    public class BrandCsvMap : ClassMap<BrandCsvResponse>
    {
        public BrandCsvMap()
        {
            Map(p => p.Id).Index(0);
            Map(p => p.Name).Index(1);
            Map(p => p.Description).Index(2);
            Map(p => p.Tax).Index(3);
        }
    }
```
