### ISSUE TITLE
Using Generic Repository

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#13]
- [ ] Generic repository; imiagine we have 100 tables then we are going to implement the repository to each respectively. We should use generic repo and provide additional repo only if needed
- [ ] Specification: how about if we want to filter data with condition or include , group by .

**Comment by iammukeshm** [comment]
As for your first point, we already have a Generic Implementation of the Repository Pattern - IRepositoryAsync. You could still use something like **IRepositoryAsync of Products** _repo if you wish to.

I will add the Specifications pattern too in a couple of days. Already have seen its use case with the Search Feature Of MudTable.

**Comment by iammukeshm** [comment]
-- Added Specification Pattern 
https://github.com/blazorhero/CleanArchitecture/commit/ea0f5c43c2eeeb280777464da1c8c1c04bd3be23
