### ISSUE TITLE
 'StatusCode cannot be set because the response has already started.'???

### ISSUE THREAD

**Issue by supermun** [fullstackhero/blazor-starter-kit#131]
**Describe the bug**
I alway get System.InvalidOperationException: '**StatusCode cannot be set because the response has already started.'** when STARTING Project for the FIRST TIME EVERYDAY

**To Reproduce**
Just Start Project:

**Screenshots**
![image](https://user-images.githubusercontent.com/41177013/119752822-d9655c00-bec7-11eb-9236-ae7632cc63d7.png)

![Screenshot 2021-05-27 083629](https://user-images.githubusercontent.com/41177013/119753161-79bb8080-bec8-11eb-9afa-51d874a3c5a9.jpg)

![image](https://user-images.githubusercontent.com/41177013/119752934-14678f80-bec8-11eb-8031-e6b73bbb660f.png)

**Desktop (please complete the following information):**
 - OS: WIN10 64bit
 - Browser chrome v 90.0.4430.212 / firefox developer v89.0b15

**Comment by Duelbat** [comment]
I have gotten this issue too. If I re-run the app straight after then it works.
