### ISSUE TITLE
There is no registered service of type

### ISSUE THREAD

**Issue by jccirs09** [fullstackhero/blazor-starter-kit#132]
![Error](https://user-images.githubusercontent.com/6688028/119758327-ee96b680-bed8-11eb-84e5-74b4a034160f.PNG)
I followed and re-trace and still not able to make it work. i'm adding new manager for new table.

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/119760652-f48e9680-bedc-11eb-95ae-09234a3ec5b2.png)

**Comment by jccirs09** [comment]
@neozhu Thank you for your time, I still didn't get it. I used the format from Document and the rest of the function to my new entity table. Also injected at _imports the new Manager. your help is greatly appreciated

**Comment by jccirs09** [comment]
![Error2](https://user-images.githubusercontent.com/6688028/119764179-86999d80-bee3-11eb-8d11-f89d52699991.PNG)

**Comment by neozhu** [comment]
See picture below for reference
![image](https://user-images.githubusercontent.com/1549611/119766857-59032300-bee8-11eb-9e02-2ccce3f92c55.png)
![image](https://user-images.githubusercontent.com/1549611/119766858-59032300-bee8-11eb-9b6c-00b37bd59ee2.png)

**Comment by jccirs09** [comment]
![manager](https://user-images.githubusercontent.com/6688028/119769413-00825480-beed-11eb-8be3-47f6ae1c5b29.png)

**Comment by jccirs09** [comment]
@neozhu I followed the same pattern, And I don't get it how to make the new service / manager work. @iammukeshm @unchase

**Comment by unchase** [comment]
@jccirs09 did you try to debug `AddManagers` extension method? Did you register a new service through it?

**Comment by iammukeshm** [comment]
Hi,

FYI,
`AddManagers` is a part of the `BlazorHero.CleanArchitecture.Client.Extensions.WebAssemblyHostBuilderExtensions.cs` file.I wrote this method to auto-register all the interface-implementation without having to manually register each of them in the container.

The only point to note is that you need to inherit from IManager on your Manager's interface. I guess you might have missed this.

For ex,
`public interface IAuditManager : IManager`

And make sure that your Managers are all in the namespace `BlazorHero.CleanArchitecture.Client.Infrastructure.Managers`.

Regards

**Comment by jccirs09** [comment]
@iammukeshm Yes I followed your structure, and the managers are under BlazorHero.CleanArchitecture.Client.Infrastructure.Managers.
As you can see, base on my screenshot they're implemented same as the example.

**Comment by iammukeshm** [comment]
can I debug your repository? is it available?
