### ISSUE TITLE
ASP.NET Core 5.0 MVC 

### ISSUE THREAD

**Issue by urmatgit** [fullstackhero/blazor-starter-kit#134]
Great project! Thanks for that. 
And please add to this solution ASP.NET Core 5.0 MVC web project. Because in this solution contains  the Application Core and the   Infrastructure  layers are more accurate.
Thanks.

**Comment by neozhu** [comment]
I think you can refer to other projects like https://github.com/ardalis/CleanArchitecture, there is  a  difference between this project and the MVC project.
