### ISSUE TITLE
Question: Register services/ interface and performance?

### ISSUE THREAD

**Issue by supermun** [fullstackhero/blazor-starter-kit#147]
I wonder if registering more and more services/ interface-implementation reduces client performance? eg: slower loading, slower processing capacity?
![1](https://user-images.githubusercontent.com/41177013/120259643-8cfe8f80-c2be-11eb-8e4e-1bdda401ebf4.jpg)
![2](https://user-images.githubusercontent.com/41177013/120259648-8ec85300-c2be-11eb-93c4-270b63a273b1.jpg)
Please explain it to me @iammukeshm , @unchase

**Comment by ANMSalman** [comment]
I was wondering the same. Isn't _Import.razor supposed to be the file where we add only the common things? wouldn't injecting every service here mean that every service will be injected into all the components? even when they are not being used? Wouldn't it break SOLID?

**Comment by unchase** [comment]
You can only inject dependencies where you need them. Using `_Imports.razor` is optional in this case.

**Comment by supermun** [comment]
thanks @unchase !
