### ISSUE TITLE
Multi user ?

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#15]
Hi Mukesh!
Amazingly insane project dude! The speed of development makes me feel decidedly ordinary  :)

Just one question: I see when making entries to the DB, its multi tenant?  What I mean, is that if I as admin add new category, it does not show for the normal user? I read that this template may have the ability to switch between single user/DB and multi? If so, is it implemented or configurable at this point?

Many thanks for the great work!
Luke Vincent

**Comment by iammukeshm** [comment]
Hi, Thanks!
The Ids are stored to maintain audit logs only.
Unfortunately, this feature is not yet implemented. But will be added in a future release. I am closing this issue for now.
