### ISSUE TITLE
MySql support

### ISSUE THREAD

**Issue by Killers0992** [fullstackhero/blazor-starter-kit#150]
**Is your feature request related to a problem? Please describe.**
Problem because of current version dont have any option to do that and if i want to that i need to redo most tuff

**Describe the solution you'd like**
Just option to use mysql as connection

**Describe alternatives you've considered**
Maybe other sqls if mysql is really yes

**Additional context**
i tried using pomelo.mysql and somehow worked but errors while doing migration

**Comment by iammukeshm** [comment]
Someone was kind enough to have already mentioned the steps to integrate with MySQL. It's quite simple.

https://github.com/blazorhero/CleanArchitecture/issues/75

Here you go - #75
