### ISSUE TITLE
App crash while Onload

### ISSUE THREAD

**Issue by SaddamBInSyed** [fullstackhero/blazor-starter-kit#152]
**Describe the bug**
I have using the latest version of the code but the application get crashing /error while starting the app as like below attached image
 
**Screenshots**  
![image](https://user-images.githubusercontent.com/10062672/120611436-40a18400-c465-11eb-8aad-29529ce9d9d7.png)

**Comment by neozhu** [comment]
by the way, how do I catch server-side exception message in blazor?
e.g. 
server-side in controller action  throw new exception ("my custom error message"); blazor catch and show alert this message

**Comment by iammukeshm** [comment]
Did you try to drop the existing database if any, and update the DB again? Also, try to clear the cache (CTRL+F5)
