### ISSUE TITLE
Windows Authentification

### ISSUE THREAD

**Issue by CedricBournazaud** [fullstackhero/blazor-starter-kit#153]
Possibility to use windows authentication for an intranet with username of AD and Group ?

**Comment by unchase** [comment]
Possibly should implement [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) integration. [See](https://identityserver4.readthedocs.io/en/latest/topics/windows.html).
It has many other providers.

**Comment by unchase** [comment]
Or [Keycloak](https://github.com/keycloak/keycloak) as identity provider.
