### ISSUE TITLE
Question: Adding another table/crud or more tutorials about BlazorHero.

### ISSUE THREAD

**Issue by LonkingPark** [fullstackhero/blazor-starter-kit#157]
Hello, I am a beginner when it comes to programming so my question may seem trivial or even offensive. The MudBlazor community (on their Discord) has written about BlazorHero and I am curious about the project and its capabilities.

How to add another CRUD or table view to BlazorHero architecture? I have reviewed all of Mr. Mukesh's tutorials from Getting Started to blazor-crud-using-mudblazor.
I know how MudBlazor works so the front-end itself is not a big problem for me (I guess :)) but I don't know how to add a new table. Everything gets complicated when I need to add services (CustomerService and ICustomerService)
 I would like to add E.g. New CRUD with regular customers (their phone number, Loyalty card number etc) to Blazor Hero project.
Does anyone have any tutorials or articles on how even a novice user can implement something like this? :)

PS: Is there any chat related to BlazorHero like Discord or Gitter for example?

**Comment by iammukeshm** [comment]
Hi, I would suggest you debug the functionality of the existing API controllers like Product / Brand. You should get a complete idea of the data flow. Moreover, this is a very straightforward and simple API/Client Architecture with CQRS Patterns. There are several links to useful tutorials on the homepage of BlazorHero. It should help you a lot.

**Comment by LonkingPark** [comment]
Thanks for the quick reply, will study the code and the rest of your blog posts. :)
If I have any more questions then post here on Github? Or there is an "Newbie" zone? :)

**Comment by MizanulIslam** [comment]
https://github.com/blazorhero/CleanArchitecture/wiki/Beginners-Guide---How-to-Add-new-functional-Page
