### ISSUE TITLE
After cloning and building the project

### ISSUE THREAD

**Issue by jquinterocortes** [fullstackhero/blazor-starter-kit#16]
**Describe the bug**
I went to the repo and clone it in Visual Studio 2019, and after building i found the following error;

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Repos\Training\BlazorHero - Clean Architecture Template\BlazorHero.CleanArchitecture\Server\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	BlazorHero.CleanArchitecture.Server	C:\Program Files\dotnet\sdk\5.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

**To Reproduce**
1. Go to repo
2. Clone the repo on Visual Studio 2019
3. See error

**Expected behavior**
The solution build without issues

**Screenshots**
![build issue](https://user-images.githubusercontent.com/4855128/111558906-98c9c380-875d-11eb-9414-94bade25d43d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2019 Community Edition 
 - Version 16.9.2

**Additional context**
I tried to do a dotnet restore in the project and found the following error:

 dotnet restore
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.201\NuGet.targets(131,5): error : Found invalid data while decoding. [C:\Repos\Training\BlazorHero - Clean Architecture Template\BlazorHero.CleanArchitecture\Server\BlazorHero.CleanArchitecture.Server.csproj]

**Comment by 274188A** [comment]
try opening a PowerShell session an run

```
dotnet --info
```

It may shed some light on what you have running for .net
