### ISSUE TITLE
Search in tables not working as expected when there are several pages.

### ISSUE THREAD

**Issue by paferpo** [fullstackhero/blazor-starter-kit#171]
**Describe the bug**
Search functionality in tables is not working as expected, it does filter and show the elements which are currenty displayed in the list, but not the ones that are in a different page of the table.

**To Reproduce**
1. Go to Products (having more than 10 records so that there are more than one page of results in the table)
2. Search for a Product that is in a different page than the current one, e.g. page 2.
4. The records matching the searched string won't show up, the table will be empty, you will only see them if you go to the page where they are.

**Expected behavior**
The records matching the search string should be shown doesn't matter in which page of the table they are.

**Comment by paferpo** [comment]
@unchase I have tried the fix (applying the changes from your PR). It works if you search from the first page but if you are in, for example, second page of results, again the filtering doesn't work.

**Comment by unchase** [comment]
Hi, @paferpo 
The filtering works correctly on the second page, but you get a response without going to the first page after the search.

**Comment by paferpo** [comment]
Hi, @unchase
You get the response with the filtered results but the view is not updated to show them. You should see the results after your search irrespectively of the page you currently are. Otherwise it's not very user friendly, is it?

**Comment by unchase** [comment]
Fixed in https://github.com/blazorhero/CleanArchitecture/pull/173/commits/d98f0b06f63582e181c9f58bf76264965ea267e2
Check, please

**Comment by paferpo** [comment]
Now it's perfect, thanks! 🎉
