### ISSUE TITLE
[Question] Is the authentication with a JWT Token safe? 

### ISSUE THREAD

**Issue by NPadrutt** [fullstackhero/blazor-starter-kit#172]
Hey!
Sorry if that is a stupid question, but with the whole debate about Identity Server in the templates and from what I find online I'm kinda confused / unsure. But is the kind of authentication via a JWT token secure? 
As I understand IS4 does basically the same thing, just in a standardized way. From what I read as long as you send them via https and validate them on receiving (which I presume will happen here) you're fine. Is that correct or is there more to it? Or should one use something like IS or OpenIdDIct for a productive app?

**Comment by chrisgate** [comment]
JWT Token is safe but it save if you implement it right.
This is template i can say it is implemented with best practices.

**Comment by NPadrutt** [comment]
@chrisgate thanks for your response and sorry my late response. I somehow didn't see it.
