### ISSUE TITLE
Error when trying to log in as admin

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#176]
I updated the database, then tried to log in.

![image](https://user-images.githubusercontent.com/46680351/121293926-9af88400-c940-11eb-8627-1fc15c38c906.png)

**Comment by iammukeshm** [comment]
I do not see this issue on my end. Maybe could you check if you have the keys configured in appSettings.json? under AppConfiguration?

**Comment by Duelbat** [comment]
Spot on Mukesh! I had tampered with the SECRET key in appSettings.json file. All working fine now!
