### ISSUE TITLE
Beginners Guide - How to Add new functional Page

### ISSUE THREAD

**Issue by MizanulIslam** [fullstackhero/blazor-starter-kit#177]
Hi Mukesh,
I am a beginner , I don't Where to Post this
Document Title --  **Beginners Guide - How to Add new functional Page**

1 	**Domain**
1.1	Add Entity and Properties
1.2 	Make it child of  AuditableEntity

2 	**Application**
2.1 	Add Folder - Xyz in Features
2.2	Add Folder Commands, Queries, Response
2.3	Add xyzQueryResponse in Response Folder (make it public), then add the Query in Query Folder
2.4	Add Command in Commands Folder (make it public)
2.5	Add XyzProfile in Mapping Folder,	Make it Child of Profile (AutoMapper)
2.6	Add mapping profile for different entity and response,Commands

3 	**Server**
3.1	Add xyzController , make it child of baseapicontroller
3.2 	Controller Name should be as co relate to the link in route folder
3.3 	Add Authorize with permissions and Implement Methods

4 	**Infrastructure**
4.1 	Add Entity Class in DbContext
4.2 	PAckage Manager Console - add migrations and Update database
4.3	Add Repository Changes (as per required Logic)
4.4	Update Database Seeder
4.5	Infrastructure.Services.Identity
	In RoleServices.GetAllPermissionsAsync  
	Add -- allPermissions.GetPermissions(typeof(Permissions.XYZ), roleId);

5	**Shared** 
5.1	Add static Xyz Class in Permisions 
5.2	Add/ Update the  PermissionModules
5.3	Add Cache Key in Constants.Appication.ApplicationConstans
	-- public const string GetAllSaleInvoiceCacheKey = "all-salesinvoices";

6 	**Client.Infrastructure**
6.1	(Add Folder XyzManager in Manager Folder)
6.2	Add IXyzManager Interface 
6.3	Add XyzManager Class , Make Both Public
6.4	In xyzManager Implement Methods and HTTP client
6.5	Add XyzEndPoint.cs in Routes Folder (http link to the controller)
	Link name should match the controller Name.
6.6	Add Link to SideBar  in NavMenu.razor

7 	**Client**
7.1	Add New-Folder in Pages 
7.2	Add Razor Component -- xyz.razor
7.3	Add class file -- xyz.razor.cs, Make it Partial 
7.4	Add resources file in resources folder (optinal)
7.5	Add Manager reference in _Import
7.6	Add Link to SideBar  in NavMenu.razor

**Comment by supermun** [comment]
In my opinion:
**1 Domain**
1.2: (Optional)

**2 Application**
2.7: Add Interfaces (IRepository / IService)
2.8: Add Validators (Optional)

**5 Shared**
5.3: (Optional)

**6 Client.Infrastructure**
--> Remove 6.6

**7 Client**
7.5: (Optional)

**Comment by iammukeshm** [comment]
I moved the data here - https://github.com/blazorhero/CleanArchitecture/wiki/Beginners-Guide---How-to-Add-new-functional-Page

Thanks :)
