### ISSUE TITLE
No DTOs?

### ISSUE THREAD

**Issue by TCrosmanDSI** [fullstackhero/blazor-starter-kit#178]
Hey,

I've been reviewing the code to BlazorHero and I am really impressed.  My question is regarding DTOs.  I noticed you return the actually EntityFramework Entities rather than map DTOs.  Is there a reason you chose to bypass this common step?

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/121614972-6d235480-ca92-11eb-8646-976b15324631.png)

GetAllPagedProductsResponse class as a DTO class, right?

**Comment by chhinsras** [comment]
DTO = Response , Request classes

**Comment by iammukeshm** [comment]
I guess we are not returning Entity object classes anywhere. We have mappers and response classes in the MediatR handlers.
