### ISSUE TITLE
Add support for Azure Active Directory

### ISSUE THREAD

**Issue by TCrosmanDSI** [fullstackhero/blazor-starter-kit#179]
I understand that this is something we really should do on our own, but should personally I would love to see other login providers (specifically Azure AD) added to the template.

In my case, I actually plan to only allow users who are authenticated with my Azure AD, but still want to leverage the power of Microsoft Identity.

**Comment by neozhu** [comment]
Is it possible to incorporate with Identity Server 4.  but it's a little too weight. 

What's the easily way base on Windows AD single sign-on solution?

**Comment by unchase** [comment]
@neozhu It is better to implement [keycloak](https://github.com/keycloak/keycloak) as it has a free license and more features.

**Comment by nbiada** [comment]
Go with OpenIDDict (IdentityServer is no more free) - https://github.com/openiddict/openiddict-core
or you can use Azure AD B2C for the first 50.000 user / month for free.

Azure AD B2C is the right choice for a public website, it's easy to implement and can have multiple external providers (like Azure AD with External Identities, but without the restriction of AD):

![image](https://user-images.githubusercontent.com/4179320/123982606-76ce1700-d9c3-11eb-83b4-fb47703a03a9.png)
