### ISSUE TITLE
Wasm startup-login issue

### ISSUE THREAD

**Issue by jomski77** [fullstackhero/blazor-starter-kit#182]
I just installed fresh copy using nuget. Set the server version project as startup and updated the database on migrations. The server version starts up fine but when I change/use the startup to the wasm version it crashes. I'm probably missing something.

![s1](https://user-images.githubusercontent.com/68258116/121663678-3fadc980-cad9-11eb-9b9c-bfcace5e18d3.PNG)
![s2](https://user-images.githubusercontent.com/68258116/121663693-42a8ba00-cad9-11eb-8483-81e686087b6f.PNG)

**Comment by DanPFW** [comment]
I think this is because the database hasn't been created.  if you watch his youtube video around 7min mark, you'll see you need to select the Infrastructure project and EF commands.  I was scratching my head with this too, didn't see any comments in the readme of the repo.  https://www.youtube.com/watch?v=j7BxKN7HYjk

**Comment by jomski77** [comment]
Thank you, I actually did that part with localdb after fresh install of BlazorHero templete. (I followed thw [quickstart guide](https://codewithmukesh.com/blog/blazor-hero-quick-start-guide/ )). Then changed the server to default instance of sqlserver on my work station. The Blazor Server version works fine on both scenario, its when i change the Startup object to the Blazor Client that this error appears.

**Comment by iammukeshm** [comment]
I guess you have mistaken. This is a WASM Application with an asp.net core self-host. When you set the Client Project as the startup, the API doesn't get up and running, and hence you see these errors. You want the API project as startup, as it has reference to client project as well.
