### ISSUE TITLE
Can not create project with latest template

### ISSUE THREAD

**Issue by sjahongir** [fullstackhero/blazor-starter-kit#184]
I install the latest template using the following command:
`dotnet new --install BlazorHero.CleanArchitecture::2.1.0`

Then I run the following command to generate the project:
`dotnet new BlazorHero.CleanArchitecture -n MyApp`

But there is not the latest source code in the generated project.

For example there is no `@attribute [Authorize(Policy = Permissions.Brands.View)]`
![image](https://user-images.githubusercontent.com/16816791/121759661-386dd680-cb40-11eb-88e0-0b2b625d29bf.png)

**Comment by iammukeshm** [comment]
The latest source code is not added to the new version. Will do it soon as testing is needed.
Thanks
