### ISSUE TITLE
Some bugs occured when running the project

### ISSUE THREAD

**Issue by ngoquoctoandev** [fullstackhero/blazor-starter-kit#187]
**1. Dashboard**
When adding any new product, to the dashboard, the client-side will display duplicate Products and Bands every time it is added. If add 10 products, it will show 10 times like that.
![image](https://user-images.githubusercontent.com/78490340/121800668-70b70700-cc5d-11eb-94cc-a131013bd18d.png)

**2. Chat**
I think this is a bug, not a feature. If a user has just registered an account but has not yet authenticated the email or the user is not activated. The chat section will list all users in the database. I think we better improve this function.

- Show only activated users
- Or only admin can chat with all users, and users can only chat with admin or manager.
- Or users can create their own chat rooms

![image](https://user-images.githubusercontent.com/78490340/121800846-503b7c80-cc5e-11eb-9b00-dadffe711ee1.png)

If the user sends the message many times, but no one has replied. I think all the messages should be combined. Instead of each message having to display the avatar, username, time...

![image](https://user-images.githubusercontent.com/78490340/121801057-99400080-cc5f-11eb-88ac-cef32222774e.png)

**Comment by unchase** [comment]
Hi, @z2hteam 

I have implemented **1.** and **2.** in https://github.com/blazorhero/CleanArchitecture/pull/173

> If the user sends the message many times, but no one has replied. I think all the messages should be combined. Instead of each message having to display the avatar, username, time...

Like this?

![image](https://user-images.githubusercontent.com/29679226/121924247-66236d00-cd44-11eb-90d1-40f86d6e9dff.png)

I think it looks worse.

**Comment by ngoquoctoandev** [comment]
I think maybe the user interface should be taken care of. The distance between objects is too far apart, making it closer and smaller like Facebook Messenger...
