### ISSUE TITLE
General documentation

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#188]
So I am first to acknowledge the work and effort gone into this project, which is substantial. I have been looking at the www.abp.io template for comparisons. What they have is substantial documentation and this really helps, in fact its a deciding factor for me when choosing a template. I feel that if this level of documentation were to be included in Blazorhero, this template would be the real deal and its adoption would skyrocket!
Thanks for all the great work Mukesh.

**Comment by iammukeshm** [comment]
Agreed. But again, as I always say, really hard for me to find time for this. I am currently working on a modular monolith architecture. Once I am done with it, I will come back to BlazorHero. 

I hope you have seen the new project - https://github.com/fluentpos/fluentpos

**Comment by tedwardc** [comment]
> So I am first to acknowledge the work and effort gone into this project, which is substantial. I have been looking at the [www.abp.io](http://www.abp.io) template for comparisons. What they have is substantial documentation and this really helps, in fact its a deciding factor for me when choosing a template. I feel that if this level of documentation were to be included in Blazorhero, this template would be the real deal and its adoption would skyrocket!
> Thanks for all the great work Mukesh.

I actually bought ABP Commercial but have pivoted and chosen to go with this project instead.  ABP does have documentation but I've had lots of problems.  It seems their tools/updates break things and make it really hard to have confidence in using it long term.  If you decide to go with ABP and want an active license cheap let me know :)

Keep up the great work Mukesh - just bought you a few coffees :)

**Comment by iammukeshm** [comment]
I would rather go with a solution I understood and built than go with ABP with all its complexities. It's an awesome framework, yet too deep that you get lost in it. 

My main idea was to build a simple solution that developers can understand at the first glance with bare minimal documents. But apparently, blazorHero has grown to an extent that, it needs some documentation for itself. 

@Duelbat  I have decided to open a documentation website for blazorHero - https://blazorhero.github.io/docs/
PS - I set it up just yesterday only, you would probably not find any docs yet. But it will be added on with time. Also excepting a lot of community contributions to the docs repo (you can find it at https://github.com/blazorhero/docs/ ). This will be linked to a .net or .com domain in a couple of weeks.

@tedwardc  Thanks for the coffees! :)

**Comment by FrancoisMongeau** [comment]
FWIW, IMHO: I've been looking/reading about these frameworks for a while. If you read recent comments about ABP you get the feeling their product is unstable/bloated, and then you need to buy the Commercial license, and then the support is lacking, and the Product is complex («big learning curve») - but some long term users love it. 
For me, after looking everywhere I could, there are 3 finalists for my project: ABP, BlazorHero and Oqtane. 
It looks to me BlazorHero is not as complex as Oqtane on the other hand Oqtane is more of a long term solution- but at this point it's just a feeling from reading the docs.
So: what's it gonna be: BlazorHero or Oqtane? _Anybody knows enough about the 2 products to make a learned comparison?_
Thanks. **And thank you Mukesh, this is great work.**

**Comment by Duelbat** [comment]
@FrancoisMongeau  Going through Oqtane docs, I see it ties you to Azure ? If this is the case, it is totally unacceptable. I would like to host my DB anywhere I choose.  I looked at ABP and was not impressed. Unless you buy the PRO version, the interface is very dated. Aesthetics count hugely these days.  If Blazorhero gets multi-tenant, for me it would be the complete package!!


![image](https://user-images.githubusercontent.com/46680351/123164555-37855f00-d4c7-11eb-931a-410023fac507.png)

**Comment by FrancoisMongeau** [comment]
I think this is just an example (from a year ago!), from what I read you are not tied to Azure at all (with v2 you can also use any from a number of popular databases). IMO Oqtane also suffers from lack of documentation - being a relatively new project (like BlazorHero?).  But I would not discard it too quickly. The owner has quite a reputation. But, as I hinted at, it may be an overkill for many projects (but it is multi-tenant), while BlazorHero might just be the right mix of features and power for most projects (and I though It was already multi-tenant?).  
But that is my HO. Being Canadian I apologize for not knowing enough (yet) about both products to offer a clear opinion.

**Comment by yellow-dragon-cloud** [comment]
I've been using Abp framework for 6+ months. Abp framework is very comprehensive and mature, and it takes time to harness its power. Its built-in theme is pretty outdated. I think Material UI is the wright path and MudBlazor is a great choice! I had to replace the main layout of my Abp project with MudBlazor components.
IMHO, Abp framework would be inspiring for the following areas:
- Multi-tenancy support
- Modular design
- Tutorials

`Blazorhero.CleanArchitecture` is a great project. I'm sure it will have a special place in Blazor development. Thanks for all the great work!
