### ISSUE TITLE
Register Screen Misaligned Fields, Validation Errors

### ISSUE THREAD

**Issue by rswetnam** [fullstackhero/blazor-starter-kit#189]
1. Go to 'https://localhost:5001/identity/users'
2. Click on 'Register'

**Expected behavior**
Register Screen

**Screenshots**
Fields Not aligned
![image](https://user-images.githubusercontent.com/2905367/122083241-8b9c8f00-cdb5-11eb-97aa-ee488e9dc8f4.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [91.0.4472.101]

**Additional context**
I am using LastPass - could that affect things?

**Comment by neozhu** [comment]
You try to upgrade the MutBlazor component to the latest version.

**Comment by neozhu** [comment]
You try to upgrade the MutBlazor component to the latest version.

**Comment by rswetnam** [comment]
I upgraded from Version 5.0.9 to 5.0.11 and it fixed the issue.
