### ISSUE TITLE
Bugs Found on version 1.0.0

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#19]
- [x] Issue: Register User Form => Username length error is not alerted 
Where:  Register User Form
- [x] Issue: Upload Picture => User Not Found Alert Error (sometime)
Where: top right menu -> account (if we go to left menu, we can upload image profile
- [x] Missing profile photo for top right side 
![image](https://user-images.githubusercontent.com/31751665/111665870-bd996600-8845-11eb-9b6f-4ea9ca83a530.png)
- [x]  When Upload profile picture for user on /account => always reload
- [x]  When Click Save Change to update profile on /account => user is logged out
- [x] Forgot Password page not found
![image](https://user-images.githubusercontent.com/31751665/111667232-16b5c980-8847-11eb-906b-29c0fc2cc338.png)

**Comment by iammukeshm** [comment]
Q.Missing profile photo for top right side
I purposely avoided it to reduce resource usage.

**Comment by iammukeshm** [comment]
When Upload profile picture for user on /account => always reload
 When Click Save Change to update profile on /account => user is logged out
 
 It has to be reloaded to update the token data. No other possible ways.

**Comment by chhinsras** [comment]
it won't be bothering as well. should be just fine
