### ISSUE TITLE
About FluentValidation

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#194]
Now, this project have addition FluentValidation put into client form, It's great!

If I want FluentValidation put into server side, Inside pipeline of MediatR.  reference. https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore.git. 
I have a question what throw invalidate messages to client UI? client ui how to catch and prompt this error message?

**Comment by iammukeshm** [comment]
the server would throw fluent validation exception wrapped in Result Wrapper class. Just show these messages on a toast notification on the client-side. 

This project has FluentValidation at the server level too.
https://github.com/fluentpos/fluentpos/blob/master/src/server/Shared/Shared.Core/Behaviors/ValidationBehavior.cs
