### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PedroVentura235** [fullstackhero/blazor-starter-kit#195]
Hey, wouldnt be best use a common resource File to all strings? 
Because like this will be a lot of repeated strings.
Also maybe replace the resx with json/xml

**Comment by nbiada** [comment]
Resx is a good choice, from my point of you.
If you use an extensions like RESX Manager (https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) you can manage all the language translation in one place.
RESX Manager can use Azure Translation engine to auto translate in a lot (lot) of languages for you, but there are other engines:

![image](https://user-images.githubusercontent.com/4179320/123980575-f0650580-d9c1-11eb-94d3-4f15c2bdf8f4.png)

in Azure the Translator Service is free of charge for 2M chars per month.

![image](https://user-images.githubusercontent.com/4179320/123981086-58b3e700-d9c2-11eb-900f-6d06cbf64ad0.png)

and using RESX you have a strongly typed namespace/class created for you in VS.
