### ISSUE TITLE
Modal Dialog Validation

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-starter-kit#196]
Example - Add New Document type

Click button to add new document type
Enter Name
Description will be showing the validation textx to say it is required.
Enter text into decription

expected to see validation error disappear as text was entered
actually saw validation error stay unless user moved-focus-away from filed

attached gif demonstrates 'bug'
![bug](https://user-images.githubusercontent.com/40014477/122699810-af137e00-d27c-11eb-8cf1-1df2b507dece.gif)

**Comment by neozhu** [comment]
It is best to initialize popup modal without validation
