### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by supermun** [fullstackhero/blazor-starter-kit#199]
Please publish new release @iammukeshm ................
I'm looking forward to creating a new project via Nuget.

**Comment by iammukeshm** [comment]
Hi, yes will publish it in the upcoming weekend. Trying to add a few functionalities and complete e2e testing. Planning for a documention website as well.

**Comment by Duelbat** [comment]
I am also hovering around waiting for this next release. I too have a project that I am going to use it in. Have to compliment you Mukesh on an amazing accomplishment with this Blazor template! I recently moved to New Zealand from South Africa and am flat broke. As soon as I can, will be buying you a truckload of coffee's !!

**Comment by iammukeshm** [comment]
#BlazorHero v2.2 is now available!

Changelog - 

- UI Improvements
- #Docker Support
- Better #Dark Theme
- Better #Permissions Management
- Code Cleanups
- #RTL Support
- Minor Bug Fixes
- Better Project Structure

What to Expect in BlazorHero 3.0?

- #Modular Architecture
- Cleaner Separation Of Code
- Dedicated #Documentation Website
- Tutorials to add new entities, controllers
- UI Updates
- Support for #PostgreSQL / #MySQL - Easy #DB Switching
- Theme Manager Integration to change UI Color Palletes / Fonts on the go.
- You can suggest your requirements as well!

**Comment by iammukeshm** [comment]
Here is the latest NuGet Package for v2.2 - https://www.nuget.org/packages/BlazorHero.CleanArchitecture/2.2.0

**Comment by boscorp** [comment]
Hi!
Is there an estimated release date for version 3.0?
