### ISSUE TITLE
Some features for your consideration

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#2]
- [ ] PDF Viewer (Printing/Download option)
- [ ] HTML Printing
- [ ] Notification
- [ ] Embed Fonts
- [x] Role Claims (Permission)
- [x] JWT Refresh Token and Revoke Token
- [x] HttpInterceptor

**Comment by elgransan** [comment]
Others nice to have features:

* **Audit Trai**: https://codewithmukesh.com/blog/audit-trail-implementation-in-aspnet-core/?utm_source=csharpdigest&utm_medium=email&utm_campaign=344
* **Console Project**: https://www.devlead.se/posts/2021/2021-01-15-my-preferred-console-stack?utm_source=csharpdigest&utm_medium=email&utm_campaign=346

**Comment by chhinsras** [comment]
Audit trail has implemented

**Comment by 274188A** [comment]
Additional Authentication options eg like Azure AD.  Authorization still kept in db - just the auth can be outsourced to externals
