### ISSUE TITLE
JWTBearerEvent bug

### ISSUE THREAD

**Issue by StefanIvovic** [fullstackhero/blazor-starter-kit#20]
**Describe the bug**
when i change expiration date to something like 20min 
next api call will result in exception in
BlazorHero.CleanArchitecture.Server.Extensions.ServiceCollectionExtensions
 OnChallenge = context =>
{
       .......
       context.Response.StatusCode = 401;  
       .......
}

**To Reproduce**
1. Go to 'identityService.cs'
2. set expires: to 20min (can also do 5 so u dont have to wait that long), when creating new JwtSecurityToken
3. run solution, delete old token and login, wait for token to expire and try to use app
4. See error - System.InvalidOperationException: 'StatusCode cannot be set because the response has already started.'

**Expected behavior**
either logout user and require new login or refresh token 

**Screenshots**
![image](https://user-images.githubusercontent.com/20303370/111707319-1bc54980-8844-11eb-9596-d2dae713c403.png)
![image](https://user-images.githubusercontent.com/20303370/111707453-5b8c3100-8844-11eb-8283-291c7add4266.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90

**Additional context**
none

**Comment by StefanIvovic** [comment]
btw, great work Mukesh :)

**Comment by StefanIvovic** [comment]
@chhinsras @iammukeshm  i have pulled commit for added refresh token but the issue still remains. i think something sinister is going on here. 

the error is the same and when i monitor dev tools/network profile picture endpoint is not working and also same thing hapend with refresh token endpoint 

![image](https://user-images.githubusercontent.com/20303370/111767715-56ac9900-88a7-11eb-9adc-dc95aaf303af.png)

https://stackoverflow.com/questions/45675102/asp-net-core-middleware-cannot-set-status-code-on-exception-because-response-ha

it looks like it has to do something with return Ok() in actions from this stackoverflow thread

**Comment by iammukeshm** [comment]
working on it . could you try to fix it from your side as well?

**Comment by StefanIvovic** [comment]
sure

**Comment by iammukeshm** [comment]
found a temporary fix. Few more commits on the way around interceptors

**Comment by chhinsras** [comment]
@StefanIvovic its related with interceptor injection issue. and Mukesh fixed it
