### ISSUE TITLE
Need to click on register x2

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#200]
When starting the app for the first time, have to click register x2 before it takes you to the register form. First click keeps you on the sign in form.

![image](https://user-images.githubusercontent.com/46680351/122856382-cf216b00-d36a-11eb-8757-552df6673b68.png)

**Comment by iammukeshm** [comment]
https://user-images.githubusercontent.com/31455818/122868673-e51e3400-d348-11eb-81fc-7430d265114a.mp4

Strange. I don't see this issue.

**Comment by Duelbat** [comment]
Please see video of the behavior. This is a freshly scaffolded Blazorhero project and after running the UPDATE-DATABASE.

https://user-images.githubusercontent.com/46680351/122891973-16beeb80-d399-11eb-9663-86db37ff6cb9.mp4

**Comment by iammukeshm** [comment]
Are you using the package generating the new project?

**Comment by Duelbat** [comment]
Hi Mukesh.
I am using the CLI to generate the project.
Cheers!

**Comment by Duelbat** [comment]
Hi Mukesh
I just tested again to make sure, here are the steps that I did to reproduce.
1.) dotnet new BlazorHero.CleanArchitecture -n Artist
2.) Changed localdb to sqlexpress (connnection string)
3.) update-database in package manager

Definitely taking 2 clicks to get to the register form.
Thanks, Luke

**Comment by iammukeshm** [comment]
Could you clone the repository locally and try the same? 

I will be releasing a new version of the nuget package in a few days. Could you let me know if you face issue with the latest repository.

**Comment by Duelbat** [comment]
Hi Mukesh
I cloned the project. Had to install Docker for it to compile.
The behavior is still the same, need to click x2 for registration dialog. 
Cheers.

**Comment by iammukeshm** [comment]
Could you check if there are any exceptions logged in your browser's console log?

**Comment by iammukeshm** [comment]
Did you need docker to compile? What was the issue you were facing without docker?

**Comment by Duelbat** [comment]
When the app starts, these are the messages in the console....  

![image](https://user-images.githubusercontent.com/46680351/123050176-8645e100-d454-11eb-9c69-94e698ef8769.png)

**Comment by Duelbat** [comment]
In in terms of  Docker, I clicked the "Use template" to add to my repo. I then ran through the usual steps to run the app and it was looking for Docker, and failed to compile. I then installed Docker and all worked.

**Comment by iammukeshm** [comment]
Could you try in a different browser or disable caching and test? I am not sure why it tries to authenticate you while going to register  page.

**Comment by Duelbat** [comment]
I changed to Firefox and the 2x click is now gone! So definitely something local to my Chrome.
But the Authorization error still shows up in Firefox, screenshot below is from Firefox.

![image](https://user-images.githubusercontent.com/46680351/123055920-7c26e100-d45a-11eb-9646-0df62f06e468.png)

**Comment by iammukeshm** [comment]
This should be the auth middleware. But I guess it's fine for you now, right? Could you close the issue if it's done?
