### ISSUE TITLE
Docker Dependency

### ISSUE THREAD

**Issue by TCrosmanDSI** [fullstackhero/blazor-starter-kit#202]
After pulling the latest changes, there is an error regarding a dependency on Docker Desktop.  I don't use docker, and this may have an impact on publishing as an Azure App.

Can't run the application now.

**Comment by TCrosmanDSI** [comment]
Here is the Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Visual Studio Container Tools requires Docker Desktop.  To get it, see https://go.microsoft.com/fwlink/?linkid=847268

For more info, please see: https://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	209

**Comment by iammukeshm** [comment]
Will fix it ASAP

**Comment by iammukeshm** [comment]
You could remove the docker-compose project and build. I guess it should work fine then?

**Comment by iammukeshm** [comment]
The projects have no dependency on Docker. It's just a build target. If you don't have Docker installed, you can always remove the docker-compose projects. Does this help?

**Comment by iammukeshm** [comment]
Alternatively, you can disable docker-compose project from the solution settings. Attaching a Screenshot.
![image](https://user-images.githubusercontent.com/31455818/123145316-5578a280-d47a-11eb-8a5d-a48d662c0be0.png)

**Comment by TCrosmanDSI** [comment]
That worked.  Thank you!

**Comment by iammukeshm** [comment]
As this might be an issue faced by many without docker, I am disabling the default docker build.
