### ISSUE TITLE
it does not open on the mobile browser

### ISSUE THREAD

**Issue by urmatgit** [fullstackhero/blazor-starter-kit#206]
Why the site does not open on a mobile browser?
The initial screen saver opens and stops there. 
through the pc, the browser works well

**To Reproduce**
1. Go to http://ihumen-001-site1.btempurl.com  with mobile browser

**Screenshots**
 
![photo_2021-06-26_23-51-20](https://user-images.githubusercontent.com/5357178/123525551-3b3cff80-d6da-11eb-85ce-29f408eb2a7e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  chrome
 - Version last

**Smartphone (please complete the following information):**
 - Device: Samsung note 9
 - OS: Android 10
 - Browser Google chrome
 - Version last

**Comment by iammukeshm** [comment]
I can see that some of the required dlls are not found. Probably recheck your publish maybe?

![image](https://user-images.githubusercontent.com/31455818/123526046-ece82a80-d6f2-11eb-9f6e-ac3942f0d7ae.png)
