### ISSUE TITLE
Current User

### ISSUE THREAD

**Issue by arkannet** [fullstackhero/blazor-starter-kit#211]
Dear sir
Hiw to get current user from application layer?
Regards

**Comment by neozhu** [comment]
You may refer to BlazorHeroContext.cs  inject ICurrentUserService to CommandHandler

**Comment by arkannet** [comment]
I replace the add new with dapper in application layer and i have to insert current user with parameter crest by so how to call current user in application layer 
Regards

**Comment by iammukeshm** [comment]
Did you try using ICurrentUserService interface? for getting the user id? I think that's all you would need.

**Comment by arkannet** [comment]
in application layer i added dapper  Example like this

`private readonly ICurrentUserService _currentUserService;
        public async Task<Result<int>> Handle(AddEditBrandCommand command, CancellationToken cancellationToken)
        {
            if (command.Id == 0)
            {
                
                    var brand = _mapper.Map<Brand>(command);
                //await _unitOfWork.Repository<Brand>().AddAsync(brand);
                using (var conn = new SqlConnection("Data Source=(local);Initial Catalog=AVDB;Integrated Security=True;"))
                {
                     

                       var parameters = new DynamicParameters();
                    parameters.Add("Id", brand.Id, DbType.Int32);
                    parameters.Add("Name", brand.Name, DbType.String);
                    parameters.Add("Description", brand.Description, DbType.String);
                    parameters.Add("Tax", brand.Tax, DbType.Decimal);
                    parameters.Add("CreatedBy", _currentUserService.UserId, DbType.String);
                    

                    conn.Open();
                    // Stored procedure method
                    await conn.ExecuteAsync("Brands_NeW", parameters, commandType: CommandType.StoredProcedure);
                }
                await _unitOfWork.CommitAndRemoveCache(cancellationToken, ApplicationConstants.Cache.GetAllBrandsCacheKey);
                return await Result<int>.SuccessAsync(brand.Id, _localizer["Brand Saved"]);
            }
            else
            {
                var brand = await _unitOfWork.Repository<Brand>().GetByIdAsync(command.Id);
                if (brand != null)
                {
                    brand.Name = command.Name ?? brand.Name;
                    brand.Tax = (command.Tax == 0) ? brand.Tax : command.Tax;
                    brand.Description = command.Description ?? brand.Description;
                    await _unitOfWork.Repository<Brand>().UpdateAsync(brand);
                    await _unitOfWork.CommitAndRemoveCache(cancellationToken, ApplicationConstants.Cache.GetAllBrandsCacheKey);
                    return await Result<int>.SuccessAsync(brand.Id, _localizer["Brand Updated"]);
                }
                else
                {
                    return await Result<int>.FailAsync(_localizer["Brand Not Found!"]);
                }
            }`


_currentUserService.UserId return Null value ?

regards

**Comment by arkannet** [comment]
Thanks i solved with _currentUserService
` public AddEditBrandCommandHandler(IUnitOfWork<int> unitOfWork,ICurrentUserService currentUserService , IMapper mapper, IStringLocalizer<AddEditBrandCommandHandler> localizer)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _localizer = localizer;
            _currentUserService = currentUserService;
        }
        private readonly ICurrentUserService _currentUserService;`
