### ISSUE TITLE
automaper instead of  Expression<Func<t, result>>

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#212]
Is it clean.
![image](https://user-images.githubusercontent.com/1549611/123886228-96445000-d981-11eb-863f-4cac93494173.png)

**Comment by nbiada** [comment]
I prefer to use the original implementation.
I haven't found any other mapping in the code for this response model.
In this case, Automapper hides the model assignment process and does not add any real value.
But this is just my opinion and I prefer to keep the code simple and readable, with no additional layers if not absolutely necessary.

**Comment by iammukeshm** [comment]
Exactly, sometimes Automapper is just an additional overhead and may give lesser control.I too personally prefer manual mapping in most of cases. But yeah, this project doesn't restrict you in any way to not use automapper. You can still use automapper if you wish to.

**Comment by neozhu** [comment]
I see. Thank you for your advice
