### ISSUE TITLE
Why does I create blazor component/page have  no code behind .cs file?

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#213]
![image](https://user-images.githubusercontent.com/1549611/123963900-7cd4ef80-d9e5-11eb-8a7d-57fb9025e02f.png)
![image](https://user-images.githubusercontent.com/1549611/123963950-8a8a7500-d9e5-11eb-8df5-71b482b24dd1.png)
![image](https://user-images.githubusercontent.com/1549611/123964003-9a09be00-d9e5-11eb-979d-be7b1e8dcb89.png)

**Comment by iammukeshm** [comment]
You have to manually add a Component.razor.cs if you want. Else you can include the C# code within the @code{} block of the razor file.

**Comment by nbiada** [comment]
You can also right-click on `@code` line and use the Quick Action **Extract block to code behind**:

![image](https://user-images.githubusercontent.com/4179320/123978968-96177500-d9c0-11eb-9092-09f6bc82dcad.png)

this will create the file for you.

**Comment by neozhu** [comment]
@nbiada,  I got it, thanks a lot.
