### ISSUE TITLE
Swagger Error

### ISSUE THREAD

**Issue by arkannet** [fullstackhero/blazor-starter-kit#214]
why swagger send me this error and my model have no field with name Id ? 
{
  "Data": null,
  "Messages": [
    "Invalid column name 'Id'."
  ],
  "Succeeded": false
}

**Comment by iammukeshm** [comment]
Which endpoint is this?

**Comment by arkannet** [comment]
its new endpoint
`namespace AVATOR.Client.Infrastructure.Routes
{
    public static class CraftsEndpoints
    {
        public static string ExportFiltered(string searchString)
        {
            return $"{Export}?searchString={searchString}";
        }

        public static string Export = "api/v1/crafts/export";

        public static string GetAll = "api/v1/crafts";
        public static string Delete = "api/v1/crafts";
        public static string Save = "api/v1/crafts";
        public static string GetCount = "api/v1/crafts/count";
    }
}`

**Comment by iammukeshm** [comment]
Probably you have not updated your database. It should be easy to debug and figure out the exception?

**Comment by arkannet** [comment]
thanks for your replay 
Actually i did , but i see any new entity most have Id Field ! 
thanks in advance 
regards
