### ISSUE TITLE
Hamburger button does not toggle visibility of sidebar in version 2.2

### ISSUE THREAD

**Issue by rswetnam** [fullstackhero/blazor-starter-kit#215]
I recently installed version 2.2 CleanArchitecture as a template to create a new project and then created a new project.  Unlike with a project created with version 2.1 clicking on the hamburger button does not hide the sidebar and make it appear - rather it just shifts the main body about 20 pixels to the left or right.  

**Expected behavior**
The side bar should toggle between visible and not.

**Comment by iammukeshm** [comment]
Could you maybe refresh the cache and try?

**Comment by rswetnam** [comment]
Blush, embarrassed - thanks -  yes works fine after clearing cache.
