### ISSUE TITLE
Blazor.Animation Feature!

### ISSUE THREAD

**Issue by Sharafudeen** [fullstackhero/blazor-starter-kit#217]
Hi,

What do you think about to add [Blazor.Animation](https://github.com/mikoskinen/Blazor.Animate)?

This may help to show presentation about the project in the startup page or Home / Introduction page or even applied to all pages as in the attached video. BlazorHero is a Webassembly project and it is the future! Users would like to do some nice animations right?

Thanks!

https://user-images.githubusercontent.com/42769344/124346979-67d3a880-dbff-11eb-8efb-4569bcee5bdd.mp4

**Comment by iammukeshm** [comment]
Sweet, you can add this animation for one or two pages maybe? If possible, pull the latest code and do your changes and submit a Pull Request. I will review it and merge it. Thanks

**Comment by Sharafudeen** [comment]
> Sweet, you can add this animation for one or two pages maybe? If possible, pull the latest code and do your changes and submit a Pull Request. I will review it and merge it. Thanks

Sure I will do it.

**Comment by Sharafudeen** [comment]
@iammukeshm Could not able to do pull request. I've created BlazorAnimate branch and also tried master branch in VS 2022 Community. It says, "Failed to push the branch to the remote repository. See the Output window for more details." but I could not see anything in the output window.

**Comment by iammukeshm** [comment]
@Sharafudeen Please pull the latest code and then try to push again.

**Comment by Sharafudeen** [comment]
@iammukeshm I get the latest and tried to "Commit & Push" but no luck. I think, I'm using two different credentials such as hotmail in VS and gmail in GitHub.. it might be the issue? Any how, here I've attached the updated files.

Do all these **steps in Client Project**: [Blazor.Animate.zip](https://github.com/blazorhero/CleanArchitecture/files/6892528/Blazor.Animate.zip)


1. Install-Package BlazorAnimate
2. Replace wwwroot -> index.html file
3. Replace Pages -> Catalog -> Products.razor & Brands.razor file
