### ISSUE TITLE
Language support for Core Application

### ISSUE THREAD

**Issue by elgransan** [fullstackhero/blazor-starter-kit#22]
You can see in the example there is some hardcoded message text to the interface, how can I translate it? Or maybe that message should be a keyword and the front end must be the responsable to translate it?

![image](https://user-images.githubusercontent.com/9949584/111715223-21199880-8832-11eb-9c88-244fd0deadbe.png)

Let me know what you want to do and I help you with this

**Comment by iammukeshm** [comment]
Hi, it might not be a good idea to implement localization at the API end. Howeevr, one viable option is to implement localization in the client side.

`_snackBar.Add(response.Messages[0], Severity.Success);`

to

'_snackBar.Add(localizer[response.Messages[0]], Severity.Success);'

or 

'_snackBar.Add(localizer["Product Added"], Severity.Success);'

I guess this is much cleaner than trying to localize the API itself as it should be kept quite stateless. Will it be possible for you to implement this change and send in a pull request?

**Comment by elgransan** [comment]
Perfect! Yes I'll do it

**Comment by iammukeshm** [comment]
@elgransan  It would be great if you could add in the pull request in a few hours. I am planning to release this project as a NuGet package for the community today.

**Comment by elgransan** [comment]
I'm think we are in a very different timezone, but now (in the morning) I'm working on it :)

**Comment by iammukeshm** [comment]
cool, will you be finishing it off in a few hours? do let me know. and don't forget to pull in the latest code. I am planning to release the package in some time. Cheers

**Comment by elgransan** [comment]
I added forgotten keywords in resource files from another languages that I don't handle, so the translation I kept it in english

**Comment by iammukeshm** [comment]
Thanks a lot! :)
