### ISSUE TITLE
NavMenu working incorrect with ver 5.0.15

### ISSUE THREAD

**Issue by Mike6x** [fullstackhero/blazor-starter-kit#220]
When I used template with MudBlazor  version 5.0.10 => I see the MudDrawer run correctly but when I upgrade MudBlazor to version 5.0.15 MudDrawer run in correctly:

![image](https://user-images.githubusercontent.com/25998007/124432831-422fd600-dd9c-11eb-8a78-0ed2dbd6152f.png)

The NavMenu can not hide !  when change status of  _drawerOpen  in MudDrawer:

![image](https://user-images.githubusercontent.com/25998007/124433018-74d9ce80-dd9c-11eb-98ed-38f9023ea9b7.png)

I do not change any thing in standard code of MainLayout.razor and MainLayout.razor.cs !

Please help !

**Comment by rswetnam** [comment]
I had a similar problem.  Refreshing the cache fixed it for me.  See issue #215

**Comment by neozhu** [comment]
@rswetnam could you share your code, I  want to change the navigation menu as well as you do!

**Comment by rswetnam** [comment]
There is nothing to share.  I just created a new application from the Template and the drawer no longer seemed to work for me.  I then tried clearing the cache (ctrl-shift-delete on Chrome) and that did nothing.  So I ran the application in private mode (ctrl-shift-n in Chrome) and it worked perfectly.  When I changed back to public mode, it continued to work.

**Comment by iammukeshm** [comment]
@Mike6x This is probably the browser cache issue. Try to clear cache (CTRL+F5) and run the application again.
