### ISSUE TITLE
[Question] Why called XService at API side when you can call it XRepository?

### ISSUE THREAD

**Issue by chrisgate** [fullstackhero/blazor-starter-kit#221]
hi Guys,
  Why named XService at API side when you can name it XRepository since it interact with DBContext/Database?
I understand the client side XService naming.

I am just curious? 

Cheers

**Comment by chhinsras** [comment]
A Repository is essentially a facade for persistence that uses Collection style semantics (Add, Update, Remove) to supply access to data/objects. It is a way of decoupling the way you store data/objects from the rest of the application.

A service supplies coordination or other "services" that are required to operate your application. They are very different in that Services don't typically know how to access data from persistence, and repositories typically only access data/objects for any services you may have.
