### ISSUE TITLE
guys, How to generate DatabaseSeeder.cs 

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#222]
hi, guys, Has anyone tell me how to generate the initial migration code file and database seeder code file.

you know it, the project of my develop branch that has a lot of migration code file, so, I want to merge these small migration code file to one initial file and database seeder file , convenience for later development

**Comment by nbiada** [comment]
Hi @neozhu ,
to recreate a migration file is enough to delete all the files in __Migrations__ and relaunch the command to create _Initial_ migration from the Package Manager or console.
The database seeding is related to application but you can read users data from XML, JSON or CSV.

I hope I have understood the question ;-)

**Comment by neozhu** [comment]
thank you, I see.

**Comment by TheCoolestEver** [comment]
how can I stop those notifications on github. I don’t understand how it works exactly

Méa Kistabish
________________________________
