### ISSUE TITLE
[BUG] Exposing server code to the clients browser

### ISSUE THREAD

**Issue by grishat** [fullstackhero/blazor-starter-kit#223]
In the continuation of the topic #175

**Describe the bug**
Project Client.Infrastructure should not have direct access on the Application project.

**Expected behavior**
All Request and Response entities, and all responses from queries and commands must be in Shared project.

**Additional context**
1. Code delivered to the clients browser, could be possible reverse-engineered.
2. Overhead of client payloads.

**Comment by iammukeshm** [comment]
Yes, this will be a part of the next release.
