### ISSUE TITLE
maybe add .editorconfig  file in the solution?

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#224]
What do you think of the approach?

**Comment by chhinsras** [comment]
what is this for?

**Comment by neozhu** [comment]
https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzers-faq?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019
