### ISSUE TITLE
Startup logo

### ISSUE THREAD

**Issue by arkannet** [fullstackhero/blazor-starter-kit#235]
i changed the startup logo like this in Index page in wwwroot but nothing change 
 

        <div style="height:100%;width:100%;margin:0;position:fixed;">
            <div class="mud-wasm"></div>
            <div class="mud-wasm" style="animation-direction:alternate-reverse;animation-duration:4s;"></div>
            <div class="mud-wasm" style="animation-duration:5s;"></div>
            <div class="mud-wasm-cont ">
                <svg width="100%" height="100%" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
                    <g>
                        <path d="M375,246c5.51,0,10-4.49,10-10s-4.49-10-10-10c-5.51,0-10,4.49-10,10S369.49,246,375,246z" />
                        <path d="M137,226c-5.51,0-10,4.49-10,10s4.49,10,10,10c5.51,0,10-4.49,10-10S142.51,226,137,226z" />
                        <path d="M510.944,191.528C509.25,188.14,505.788,186,502,186H312.499c-15.457-12.5-35.117-20-56.499-20s-41.041,7.5-56.499,20H10   c-3.788,0-7.25,2.14-8.944,5.528C-0.638,194.916-0.272,198.97,2,202l30,40c1.889,2.518,4.853,4,8,4h15l27,36   c1.889,2.518,4.853,4,8,4h15l27,36c1.889,2.518,4.853,4,8,4h59.501c15.457,12.5,35.117,20,56.499,20s41.041-7.5,56.499-20H372   c3.147,0,6.111-1.482,8-4l27-36h15c3.147,0,6.111-1.482,8-4l27-36h15c3.147,0,6.111-1.482,8-4l30-40   C512.272,198.97,512.638,194.916,510.944,191.528z M181.204,306H145l-15-20h8c5.523,0,10-4.478,10-10s-4.477-10-10-10H95l-15-20h17   c5.51,0,10-4.49,10-10s-4.49-10-10-10H45l-15-20h151.204C171.606,220.311,166,237.512,166,256S171.606,291.689,181.204,306z    M256,326c-38.598,0-70-31.402-70-70s31.402-70,70-70s70,31.402,70,70S294.598,326,256,326z M467,226h-52c-5.51,0-10,4.49-10,10   s4.49,10,10,10h17l-15,20h-43c-5.523,0-10,4.478-10,10s4.477,10,10,10h8l-15,20h-36.204C340.394,291.689,346,274.488,346,256   s-5.606-35.689-15.204-50H482L467,226z" />
                        <path d="M256,206c-27.57,0-50,22.43-50,50s22.43,50,50,50s50-22.43,50-50S283.57,206,256,206z M256,286c-16.542,0-30-13.458-30-30   s13.458-30,30-30s30,13.458,30,30S272.542,286,256,286z" />
                        <circle cx="256" cy="256" r="10" />
                    </g>

                </svg>
            </div>
        </div>

**Comment by iammukeshm** [comment]
Hi, tried refreshing the browser cache?

**Comment by arkannet** [comment]
Yep thanks
