### ISSUE TITLE
Add Scrutor for Dinamyc Dependency Injection

### ISSUE THREAD

**Issue by Artillio** [fullstackhero/blazor-starter-kit#238]
What do you think about add Scrutor 
https://github.com/khellang/Scrutor

for the Dinamyc Dependency Injection?

**Comment by iammukeshm** [comment]
Scrutor is good, But it's more of a preference rather than a necessity. It might be harder for devs to understand the DI registrations if we use Scrutor. That's one reason I decided not to adapt to it. However, I am also considering it for 3.0 for reducing the LOCs.
