### ISSUE TITLE
Adding relation between user and entities

### ISSUE THREAD

**Issue by StefanIvovic** [fullstackhero/blazor-starter-kit#239]
I really like work that has been done but there are some issues. With that said, i am having issue using user in relation with my entities. I tried to refactor code but its too much work. Core and Infrastructure folders are too granulated.  
Doman entities are in Doman and Infrastructure lib projects and now i cant use User entity for relationships. 

or maybe i am wrong, maybe there is way of using user with my entities ?

**Comment by chhinsras** [comment]
What is your problem . I don't get it

**Comment by StefanIvovic** [comment]
cant add User as navigation property to my entity. I have created my entity in myapp.Domain.Entities namespace but the user is in myapp.Infrastructure.Models.

**Comment by adimation** [comment]
You don't add navigation property for user. Just foreign ID. And get user
in your core project where your business logic is.

**Comment by iammukeshm** [comment]
It is really not a good idea to add the user as nav property. You can use the ICurrentUserService to fetch the current logged in UserId and proceed from there.

**Comment by StefanIvovic** [comment]
cool i got it
