### ISSUE TITLE
Azure Authentication

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-starter-kit#24]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
To be able to use for example Azure Authentication instead of username and password

**Describe alternatives you've considered**
n/a

**Additional context**
link to sample from microsoft for Azure Auth in a webapi: https://github.com/AzureAD/microsoft-identity-web/blob/master/ProjectTemplates/templates/WebApi-CSharp/Startup.cs

**Comment by iammukeshm** [comment]
Currently, this feature is out of scope for the project. Will be added in a future release.
