### ISSUE TITLE
Enable CLI migration

### ISSUE THREAD

**Issue by rioda78** [fullstackhero/blazor-starter-kit#240]
**Describe the bug**
cannot create migration using CLI, only PMC supported

**To Reproduce**
follow [https://codewithmukesh.com/blog/blazor-hero-quick-start-guide/](url), migrate database using PMC

**Expected behavior**
enable Cli command for migration dan update database

**Desktop (please complete the following information):**
- windows 10

How to resolve**
1. remove migration on infrastucture with PMC
`remove-migration`
2. add migration assembly to dbcontext
`.AddDbContext<BlazorHeroContext>(options=> 
                        options.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), 
                            b=>b.MigrationsAssembly("Sipd.Server")))
                    .AddTransient<IDatabaseSeeder, DatabaseSeeder>();` 
where SIPD is folder name or namespace                
2. change directory to server and running cli 
`dotnet ef migrations add Initial` anc command `dotnet ef database update`

now CLI is running well thanks for this project

**Comment by 274188A** [comment]
try this:

`dotnet ef migrations add --startup-project ..\Server\Server.csproj --context BlazorHeroContext "your comment here..." -o Migrations`
