### ISSUE TITLE
Refit Library

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-starter-kit#241]
Refit creates a strongly typed interface for the API which moves all this knowledge about URLs, request and response types into one place.

I think we could cut down on some boilerplate code, reduce the number of magic strings and improve the discoverability of the API by using the handy Refit library.

Suggested here:
https://jonhilton.net/blazor-refit/

Refit GitHub repository:
https://github.com/reactiveui/refit

**Comment by iammukeshm** [comment]
Will check this. Thanks
