### ISSUE TITLE
There seems to be a serious performance problem?

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#243]
it get stuck, When you have too much data,
Is this a problem with the underlying framework or with the component?
https://user-images.githubusercontent.com/1549611/126593424-14a66307-1fe5-4930-92eb-06ad7f0a84ab.mp4
<video src="https://user-images.githubusercontent.com/1549611/126593424-14a66307-1fe5-4930-92eb-06ad7f0a84ab.mp4" controls="controls" >您的浏览器不支持播放该视频！</video>

**Comment by iammukeshm** [comment]
@unchase  could you check on this?

**Comment by neozhu** [comment]
https://github.com/neozhu/CleanArchitecture/tree/dev
my project

**Comment by unchase** [comment]
> https://github.com/neozhu/CleanArchitecture/tree/dev
> my project

Hi, @neozhu 
There is no **Add ProductRelation** in your dev branch.
To solve the issue, I need the current state of the application in which it occurs.

**Comment by neozhu** [comment]
[keyvalues_23072021202744.xlsx](https://github.com/blazorhero/CleanArchitecture/files/6868680/keyvalues_23072021202744.xlsx)
please import this excel to keyvalues table
![image](https://user-images.githubusercontent.com/1549611/126781666-f48d4342-33e2-40a7-b4cb-c5be5310d2dd.png)
![image](https://user-images.githubusercontent.com/1549611/126781730-01ee1d45-328b-4f04-95cf-ee57995fda46.png)
I get stuck when selectd items

**Comment by neozhu** [comment]
I run the MudBlazor project performance is ok.

**Comment by neozhu** [comment]
I think this is a WASM issue.

**Comment by neozhu** [comment]
I'd like to know how to switch to run server-side mode.
I hope to realize the feature of mode switching as soon as possible
