### ISSUE TITLE
Possibility for Azure SQL Database

### ISSUE THREAD

**Issue by JohnTheBeaver** [fullstackhero/blazor-starter-kit#245]
**Is your feature request related to a problem? Please describe.**
It looks like it is not possible to change a on-prem SQL Server to Azure SQL DB. If I add the ADO connectionstring of my Azure SQL DB the process won't succeed and project not work.

**Describe the solution you'd like**
Would like to see the possibility to add the Azure SQL DB ADO connectionstring to the project settings.

Hope that it's already possible and that I'm wrong :)

**Comment by iammukeshm** [comment]
Are you able to connect to the DB Server? Make sure there is no firewall issue.

**Comment by JohnTheBeaver** [comment]
I think I'm not able to make connection. I've this Connectionstring, but get every time "Build Failed"

Appsettings.json:
`"ConnectionStrings": {
    "DefaultConnection": "Data Source=tcp:<serverName>.database.windows.net,1433;Initial Catalog=<dbName>;Integrated Security=True;MultipleActiveResultSets=True"
  },`

And connected in Visual Studio to my database in the "SQL Server Object Explorer"

**Comment by iammukeshm** [comment]
There are 2 AppSettings for BlazorHero
1. https://github.com/blazorhero/CleanArchitecture/blob/master/src/Server/appsettings.Development.json
2. https://github.com/blazorhero/CleanArchitecture/blob/master/src/Server/appsettings.json

Development AppSettings usually overrides the default appsettings in the dev environment. Thus mostly BlazorHero will be using the connection string from appSettings.Development.json

I think this should help you solve your issue.

**Comment by JohnTheBeaver** [comment]
The problem was that I used Visual Studio 2022 preview, that's using .NET6. After installing lower version of Visual Studio with .NET5 the solutions works.

@iammukeshm this one can be closed :)
