### ISSUE TITLE
Id field create by :AuditableEntity

### ISSUE THREAD

**Issue by agorota** [fullstackhero/blazor-starter-kit#246]
Hi, I'm studying BlazorHero.
I am trying to prepare an application to manage an already active database.
I followed the Wiki
_https://github.com/blazorhero/CleanArchitecture/wiki/Beginners-Guide---How-to-Add-new-functional-Page_
and for now I have managed my base tables without any particular problems.

The question is:
So specializing my tables with: AuditableEntity<Guid>
it is useful for me to have the logs for CreatedBy, CreatedOn, LastModifiedBy and LastModifiedOn
but the Id <Guid> field is also created, which is indispensable for BlazorHero code. But I already have the Id field in my tables which is called for example Customer_Id <Guid>.
The field is duplicated and therefore useless to me.
How can I do not to create and not have to manage the Id field keeping: AuditableEntity

Thank you

**Comment by unchase** [comment]
Hi, @agorota 

For example, something like this:

```csharp
public class Customer : AuditableEntity<int>
{
    [NotMapped]
    private new int Id { get; set; }

    [Column("Customer_Id")]
    public int CustomerId {
        get => Id;
        set => Id = value;
    }

    // some other properties
}
```

**Comment by agorota** [comment]
Thanks  @unchase , it works!
