### ISSUE TITLE
Is this for Noobs ?

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#247]
Hi
While I appreciate the tremendous work that has gone into this project, it seems that without decent documentation it is definitely not for noobs. So who benefits actually ?  I would suggest its the very experienced mostly ?? 

For maximum benefit, please add basic documentation. Even the current example on how to get a working page is not as clear as it should be.

Many thanks to all!

**Comment by iammukeshm** [comment]
Could you take you time and give me a list of documentation you think that would be needed?  I will prioritize it. 
Regards

**Comment by LonkingPark** [comment]
Its great for learning how Clean Architecture looks like. But I agree with Duelbat that its not so clear and documentation is lacking :)
Even after reading your guides about CQRS and Onion i still had huge troubles with adding new entity.
My recommend to start with that. Show users how they can add their own simple features. Like adding another CRUD to Catalog or change Products/Brand to their needs without breaking everything, change logo and how to setup email verification  :)
Regards.

**Comment by FrancoisMongeau** [comment]
@LonkingPark Great comment! I agree: Write a step by step tutorial for (here are 2 suggestions):
- Add a new CRUD for another entity (eg Client: FirstName, LastName, Address, Phone)
- Show how to add new properties to Product and links between entities (eg Products that have be purchased by a Client)
These are examples of suggestions, someone may think of better ones.
Cheers and thanks for the great work.
PS: I'll be happy to help with documentation once I understand how things work.

**Comment by Duelbat** [comment]
I would add:

- Complete example of setting up email functionality for email providers like Sendgrid or Mailjet. 
- Example of how to use HANGFIRE in one or two scenarios.
- Master-detail CRUD
