### ISSUE TITLE
@iammukeshm @unchase, Do you think have solution to solve MudBlazor performance problems  in WASM mode

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#253]
MudBlazor component(table, select) has performance issues when loading a lot of data ( over 200 items)  in the wasm model.

Has anyone else encountered it? Have you applied this framework to a real project?  

I asked mudblazor team  and was told that the underlying WASM issues  and it's ok in server-mode

**Comment by chrisgate** [comment]
have u consider server side pagination where u load from the server what screen as display?

**Comment by neozhu** [comment]
yes, I have using server-side paging load data. 
you try to load over 200 items with a table or select component.
I have 3 Multiselect components that each load 200 items, the operation delay is very serious

**Comment by neozhu** [comment]
fetch data 40ms,but rending component 20s.
https://user-images.githubusercontent.com/1549611/127496859-f937e97b-9ade-4df3-99b4-ed64ac6b5dd6.mp4

**Comment by neozhu** [comment]
https://user-images.githubusercontent.com/1549611/127499591-40c9230c-4282-42a2-a580-704b8d808bf3.mp4

**Comment by neozhu** [comment]
you can import brands items for testing.
This is a critical issue.

**Comment by iammukeshm** [comment]
These are some of the major issues of WASM, not necessarily MudBlazor. Hope to see some updates on this in 6.0 maybe.

**Comment by unchase** [comment]
Hi, @neozhu 
At the moment, I have not found a solution for this issue. Performance should probably get better after .NET 6 release

**Comment by neozhu** [comment]
But this problem is a bit serious, as far as the current performance is worrying, it is unacceptable for users.
@unchase , You can try importing a few thousand rows of data into the brands table.
@iammukeshm, I change to .net 6 preview framework, there is no improving.

**Comment by neozhu** [comment]
please, see the following videos, one is run wasm, the other run server,
https://user-images.githubusercontent.com/1549611/127594309-3198def2-1547-4d38-b867-959dacfdfc84.mp4


https://user-images.githubusercontent.com/1549611/127594313-de8b5c94-bf1d-4b82-a887-e732fcc1d882.mp4

**Comment by iammukeshm** [comment]
@neozhu is the data rendered at the server or client side? Each Pagination click calls the API?

**Comment by neozhu** [comment]
following code:
````
@page "/"
@using MudBlazor

<MudTable 
          Height="calc(100vh - 290px)" 
          FixedHeader="true" 
          FixedFooter="true"
          Items="@Elements" 
          MultiSelection="true" 
          @bind-SelectedItems="SelectItems"
          Hover="@hover">
    <HeaderContent>
        <MudTh>Nr</MudTh>
        
    </HeaderContent>
    <RowTemplate>
        <MudTd DataLabel="Nr">@context</MudTd>
       
    </RowTemplate>
    <PagerContent>
        <MudTablePager PageSizeOptions="new int[]{50, 500,1000,2000}" />
    </PagerContent>
    <FooterContent>
        <MudTd colspan="5">Select All @SelectItems.Count</MudTd>
    </FooterContent>
</MudTable> 
@code {
    private bool hover = true;
   

    private List<int> Elements = new();
    private HashSet<int> SelectItems=new();

    protected override async Task OnInitializedAsync()
    {
        Elements = await Task.FromResult(Enumerable.Range(0,6500).Select(e=>e).ToList());
    } 
}
````

**Comment by iammukeshm** [comment]
Do you really do this in production? Trying to load 6.5k records in one go? I think you can optimize this by paginating and stuff.

**Comment by iammukeshm** [comment]
You can also use timers or benchmarking NuGet packages to identify the bottlenecks in this code, so we have more data to analyze this issue.

**Comment by 274188A** [comment]
there's the problem right there...
![image](https://user-images.githubusercontent.com/40014477/127605472-8f3aca06-1b99-4b90-bc6b-543b05091206.png)

recommend Close

**Comment by neozhu** [comment]
I testing what fetch 2000 items of data from server-side times, It takes very little time only 20-40sm, Spend all your time rendering the UI.

**Comment by 274188A** [comment]
seriously why bring even 200 items back - no human can read over 200 in one go - it's just not going to end in a happy story.  'Paging' is your friend.

**Comment by neozhu** [comment]
> there's the problem right there...
> ![image](https://user-images.githubusercontent.com/40014477/127605472-8f3aca06-1b99-4b90-bc6b-543b05091206.png)
> 
> recommend Close

this is initialized data , it's ok, When you turn the page, it gets stuck very slowly

**Comment by 274188A** [comment]
it's not ok in my opinion and you're paying the price of bringing so much data back in one go.  continue with what you have but I would strongly recommend otherwise.  all the best!

**Comment by neozhu** [comment]
@274188A  I chose 2000 rows of data a page just to test obviously, but 200 rows of data is also very slow

**Comment by neozhu** [comment]
@274188A  now, you can import 2000 rows of data to the brands page and test it yourself in this project

**Comment by iammukeshm** [comment]
I usually paginate with 25-50 records at a time. It doesn't make sense to load 2000 or so records and give a hard time to the UI components to render it. Yes, there are projects that require you to load 6000 records in a time, but in that case, you shouldn't even use EFCore for it. Better stick to Dapper / Raw SQL and lighter UI components.

**Comment by 274188A** [comment]
> @274188A now, you can import 2000 rows of data to the brands page and test it yourself in this project

I would never bother because the amount is not realistic - to read more that 100/page is getting up there.  make sure you only bring back the columns you actually show in the grid.  if a user clicks to see details then you fetch-by-id the full object.

**Comment by neozhu** [comment]
yes, not so much data is usually loaded at once,I just found out about this problem by doing performance testing.
But I've found this problem in my projects, it's very slow when there are multiple controls that bind data on a page

**Comment by iammukeshm** [comment]
A public-facing SPA application where Customer / UX is important will never load even 50+ records at a time. This amount of data will have issues with mature client frameworks like Angular / react too. Blazor already has quite a lot of performance issues considering the usage of WASM. But this particular issue may not be related to WASM or MudBlazor as such.

**Comment by neozhu** [comment]
yes, not so much data is usually loaded at once,I just found out about this problem by doing performance testing.
But I've found this problem in my projects, it's very slow when there are multiple controls that bind data on a page

**Comment by 274188A** [comment]
so now you've shifted from 'slow to load records' to slow to bind...?

**Comment by TheCoolestEver** [comment]
Cause I have no idea how to control any of my apps. I was waiting on a direct deposit from my
***@***.***)  email account or I think I may have setup something or erased someone. Anyway. iCloud, Drive, Dropbox, Onedrive, Amazon Drive have all of my Microsoft account on each one. Subscriptions I didn’t know I have signed up for.

Méa Kistabish
105, Rue Shiwa
Amos, Québec
J9T 3A3
Canada


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by neozhu** [comment]
now, it's ok.
I found no performance issues after deploying to the IIS server. 
http://wasm.i247365.net/
http://aot.i247365.net/
I'm relieved for the moment
thank you for your response.

**Comment by 274188A** [comment]
> Cause I have no idea how to control any of my apps. I was waiting on a direct deposit from my ***@***.***) email account or I think I may have setup something or erased someone. Anyway. iCloud, Drive, Dropbox, Onedrive, Amazon Drive have all of my Microsoft account on each one. Subscriptions I didn’t know I have signed up for. Méa Kistabish 105, Rue Shiwa Amos, Québec J9T 3A3 Canada Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: 274188A ***@***.***> Sent: Friday, July 30, 2021 1:49:19 AM To: blazorhero/CleanArchitecture ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [blazorhero/CleanArchitecture] @iammukeshm @unchase, Do you think have solution to solve MudBlazor performance problems in WASM mode (#253) so now you've shifted from 'slow to load records' to slow to bind...? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fblazorhero%2FCleanArchitecture%2Fissues%2F253%23issuecomment-889645838&data=04%7C01%7C%7C96de43242fe74a52b51808d9531dc6ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637632209613874039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YJfGgAMK%2F28Ib64Gdc9ljZlzYAkyCPXsmDodIZdE5no%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUG5REUH2T42WUIMLHLXX5TT2I4N7ANCNFSM5BF74KMA&data=04%7C01%7C%7C96de43242fe74a52b51808d9531dc6ce%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637632209613883983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e4M9QvQv8SLsF5j1K3gjbLYX7LAB%2BcQZaklToe8tE%2FU%3D&reserved=0>.

@iammukeshm - possible spam...i cannot report it

**Comment by nbiada** [comment]
Just a little contribute to this closed task.
Please remember the double rendering of Blazor.
So, is far better to load data in the AfterRender instead in the Initialized.
Like this:
```C#
protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
                await LoadDataAsync();
        }
```
in the razor page you can render the entire page excluding the list/table or combo you're loading.
