### ISSUE TITLE
page layout cannot be responsive size

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#258]
![image](https://user-images.githubusercontent.com/1549611/127740547-8539dfdb-3600-4083-9462-68fedc263993.png)
Once such a problem occurs, it must be restarted
Please， Check it

**Comment by iammukeshm** [comment]
How do you get this?

**Comment by neozhu** [comment]
get last version debug running and change chrome window size

**Comment by neozhu** [comment]
https://user-images.githubusercontent.com/1549611/127755994-8fd3a4af-6f8f-4497-81d6-5b3a2741602e.mp4

**Comment by neozhu** [comment]
https://user-images.githubusercontent.com/1549611/127788928-c0c1eaee-70f8-4da3-890d-546472dac04d.mp4

**Comment by neozhu** [comment]
@iammukeshm do you have same issue?
This is weird,the console is not output any error information, but it is not responding and not refreshing page.

**Comment by neozhu** [comment]
I found chrome and edge cpu usage 100 when change window size to min.  
![image](https://user-images.githubusercontent.com/1549611/127817434-adaad13d-daed-499b-b4da-855ea8c7a353.png)
![image](https://user-images.githubusercontent.com/1549611/127819448-28ac71c9-758d-45b3-900b-eba27d3e9cd6.png)

**Comment by peteryulius** [comment]
Problem on MudHidden, I try to another ways, using ResizeListener, and have the same error.

**Comment by peteryulius** [comment]
Conflict on MudHidden Breakpoint="Breakpoint.SmAndDown"

![image](https://user-images.githubusercontent.com/8745284/128000700-921e91e8-e1b7-4c97-832f-6928e0be3df1.png)

**Comment by neozhu** [comment]
I saw use 
div class="d-none" and class="md-none" in mudblazor project

**Comment by peteryulius** [comment]
![image](https://user-images.githubusercontent.com/8745284/128003342-0de88fab-2883-47ae-bdfe-1a1961e78f52.png)

And the result like this:
![image](https://user-images.githubusercontent.com/8745284/128003426-a66048fb-17b5-4cea-b8d1-db9b1a8244b2.png)

**Comment by iammukeshm** [comment]
Please check the latest code if it solves your issue.
