### ISSUE TITLE
Concurrency edit

### ISSUE THREAD

**Issue by denadmin** [fullstackhero/blazor-starter-kit#260]
What about concurrency edit? Say two different users change document at the same time. For now changes of the first user will be lost.

I suggest: when the database changes, the UI shows the changes so the user can overwrite or abort.

**Comment by chrisgate** [comment]
i think is it a business logic that may or may not get to the clean Architecture .................
meanwhile check out this video https://www.youtube.com/watch?v=mLfhXKkxxRs

**Comment by iammukeshm** [comment]
I believe this is more of a requirement than what you can expect in a template. However, I have already implemented SingalR updates in the dashboard where the data gets updated live. You can do something similar.
