### ISSUE TITLE
How to get Created By Name and Last Updated By Name at querying?

### ISSUE THREAD

**Issue by ANMSalman** [fullstackhero/blazor-starter-kit#261]
How do I get the CreatedBy user's Name and LastUpdateBy user's Name at querying? Let's say I want to display who created a product and who updated it last, how do I get it? Because the feature for products query is in the Application layer and identity-related entities are in the Infrastructure layer. In short, how do I add created by user's name and last updated by user's name in GetAllProductQuery's response?

**Comment by chrisgate** [comment]
First, Do u understand the Onion pattern used?
That is first thing in having flexibility with the clean architecture.
For me i have converted the Onion pattern to my normal way of coding but i understand the Onion first.

Cheers to guys behind the template !

**Comment by ANMSalman** [comment]
@chrisgate, I do understand the Onion Architecture. That's why I don't want any external dependency like identity in my Domain. Infact, I'm using BlazorHero template on my project. I don't understand what you are trying to convey. I do have some workaround to achieve this. But I wanted to know if there is a better way. How would you suggest that you would achieve this?

**Comment by neozhu** [comment]
@ANMSalman, You can rewrite the following code to replace userid with username
```
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            foreach (var entry in ChangeTracker.Entries<AuditableEntity>())
            {
                switch (entry.State)
                {
                    case EntityState.Added:
                        entry.Entity.CreatedBy = _currentUserService.UserId;
                        entry.Entity.Created = _dateTime.Now;
                        break;

                    case EntityState.Modified:
                        entry.Entity.LastModifiedBy = _currentUserService.UserId;
                        entry.Entity.LastModified = _dateTime.Now;
                        break;
                }
            }

            var result = await base.SaveChangesAsync(cancellationToken);

            await DispatchEvents();

            return result;
        }
