### ISSUE TITLE
Bug when change a page size

### ISSUE THREAD

**Issue by urmatgit** [fullstackhero/blazor-starter-kit#264]
- OS:  Windows 10
 - Browser  Microsoft Edge, Chrome
 

https://user-images.githubusercontent.com/5357178/128163754-8fd774f6-05fc-4fb0-a678-c6acadffd6a4.mp4

**Comment by neozhu** [comment]
I have already reacted to this problem.  use div class instead of mudhide！ see mudblazor project code.

Have you used the framework in your projects and have you had performance issue? I feel that very slower then html page.

**Comment by iammukeshm** [comment]
Will be addressed in the next release

**Comment by peteryulius** [comment]
Your issue already on this link https://github.com/blazorhero/CleanArchitecture/issues/258
