### ISSUE TITLE
Hello, everyone, I also worked on a Razor Pages  CleanArchitecture Project

### ISSUE THREAD

**Issue by neozhu** [fullstackhero/blazor-starter-kit#272]
https://github.com/neozhu/RazorPageCleanArchitecture.git
Reference this project and jasontaylordev/CleanArchitecture project. 
The front-end is replaced with a Razor Page(simplest), please review it.

**Comment by iammukeshm** [comment]
Cool. Probably put this up in our Discord or FB Page, maybe the ASP.NET FB group as well.
