### ISSUE TITLE
More than one DB Context [Main DB context and Routing DB context]

### ISSUE THREAD

**Issue by rjabuya** [fullstackhero/blazor-starter-kit#274]
**Issue Description**
Currently the template uses one db context registered on Start Up. My issue is that I wanted two have two databases...one routing database and another main database. 

From the login in you enter institution code then when this connects to routing database that now redirects to another main database and that is when the user logs in to the main database [changing to the main db context]

Please advise any possibility/any reference you may have in implementing the same on Blazor Hero Template.

**Comment by nbiada** [comment]
Do you want to use the main database only for data or also for user authorization?
Should be harder to duplicate the authorization system, sending cross access token between them.

**Comment by rjabuya** [comment]
The main database will handle data and authorization but routing database is used for routing to the main context only so i.e. on main context class will just have Institution code which helps it to know the main context/database to connect to.

**Comment by nbiada** [comment]
I think that is easier to create a simple prelogin page connecting to the routing database.
When the user select or enter the institution code, the code behind connects to the routing database, read the required data and redirect to the home page of the app.
The app needs to receive a parameter from the query string (route) in order to connect to the main database requested.
And after that will be possible to authenticate the user.

Look at this post:
https://stackoverflow.com/questions/36816215/dynamically-change-connection-string-in-asp-net-core

In practice you can define a placeholder like:
```C#
"IbmDb2Formatted": "DATABASE={0};SERVER=servername;UID=userId;PWD=password"
```
and connect to the database specified in the query string:
```C#
var httpContext = serviceProvider.GetService<IHttpContextAccessor>().HttpContext;
            var httpRequest = httpContext.Request;

            // Get the 'database' querystring parameter from the request (if supplied - default is empty).
           // TODO: Swap this out for an enum.
            var databaseQuerystringParameter = httpRequest.Query["database"].ToString();

            // Get the base, formatted connection string with the 'DATABASE' paramter missing.
            var db2ConnectionString = Configuration.GetConnectionString("IbmDb2Formatted");

            if (!databaseQuerystringParameter.IsNullOrEmpty())
            {
                // We have a 'database' param, stick it in.
                db2ConnectionString = string.Format(db2ConnectionString, databaseQuerystringParameter);
            }
            else
            {
                // We havent been given a 'database' param, use the default.
                var db2DefaultDatabaseValue = Configuration.GetConnectionString("IbmDb2DefaultDatabaseValue");
                db2ConnectionString = string.Format(db2ConnectionString, db2DefaultDatabaseValue);
            }

            // Build the EF DbContext using the built conn string.
            options.UseDb2(db2ConnectionString, p => p.SetServerInfo(IBMDBServerType.OS390));
```
I've used this method in the past.

**Comment by rjabuya** [comment]
Thank you very much. This will really help my solution. Let me go through this.

**Comment by nbiada** [comment]
Hi @rjabuya , if my answer resolves your problem, please close the issue.
Thanks in advance
