### ISSUE TITLE
FluentValidation against MudSelector

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-starter-kit#275]
If using a `MudSelect` component, and also using FluentValidation, the validation works but the **message** from the failed validation does not show.  This leaves the user a bit perplexed as to what just failed.

I've had to hack around this but adding textfields next to the MudSelect which is less than ideal.

**Comment by 274188A** [comment]
Found the using the following properties on the MudSelect is the best option:
  Required="true"
  RequiredError="some message..."

Meanwhile in the Validator, just use the rule as normal to disable the Save button

Together this works nicely

**Comment by TheCoolestEver** [comment]
Méa Kistabish
