### ISSUE TITLE
Clicking on Hangfire menu item yields error

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#28]
I was clicking around in the application, just random clicks and entering a few products etc. 
When clicking on the HANGFIRE menu item, I got an error - please see attached screenshot. Unfortunately it seems to be random. I have been trying to create the steps necessary to reproduce but have not succeeded. 

![image](https://user-images.githubusercontent.com/46680351/111848300-a22a7a00-896f-11eb-8f07-df323432c1fe.png)

Thanks, Luke.

**Comment by iammukeshm** [comment]
Hi, this is an issue which occurs when Hangfire schema is not created by default. Probably for some reason, the schema creation was skipped. I will try as well if i could reproduce this issue. Thanks
