### ISSUE TITLE
EF Core query best practice

### ISSUE THREAD

**Issue by Artillio** [fullstackhero/blazor-starter-kit#283]
HI guys!
I have some sql query with multiple join on multiple table for statistic and analytics .
I'm new with EF core.
what are the best practices to convert sql query to ef core? Is there something like stored procedures that are better to use?
thanks !

**Comment by nbiada** [comment]
Hi,
if you want to convert your project to a full EF Core you need to convert any SQL queries and DML to linq.

If you prefer, due to complexity or time to invest, maintain your original SQL code, go with stored procedure and use EF Core and linq to manage the resulting datasets.

**Comment by Artillio** [comment]
Nice tips!
How can I exec query on EF Core?
I can't find out how to do it.

**Comment by unchase** [comment]
@Artillio https://docs.microsoft.com/en-US/ef/core/ (for example, https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)

Or https://www.entityframeworktutorial.net/efcore/entity-framework-core.aspx

**Comment by Artillio** [comment]
Really Thanks!
Now I try !!

**Comment by agorota** [comment]
> 
> 
> @Artillio https://docs.microsoft.com/en-US/ef/core/ (for example, https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
> 
> Or https://www.entityframeworktutorial.net/efcore/entity-framework-core.aspx

Hello
Very interesting, could you post a small example of a query or execute a storedprocedure to use in BlazorHero?
Maybe a simple query to replace /Application/Features/Brands/GetAll/GetAllBrandsQuery.cs

How do I access the BlazorHero DbContext from here?

```
public async Task<Result<List<GetAllBrandsResponse>>> Handle(GetAllBrandsQuery request, CancellationToken cancellationToken)
        {
            Func<Task<List<Brand>>> getAllBrands = () => _unitOfWork.Repository<Brand>().GetAllAsync();
            var brandList = await _cache.GetOrAddAsync(ApplicationConstants.Cache.GetAllBrandsCacheKey, getAllBrands);
            var mappedBrands = _mapper.Map<List<GetAllBrandsResponse>>(brandList);
            return await Result<List<GetAllBrandsResponse>>.SuccessAsync(mappedBrands);
        }
```
Thanks

**Comment by nbiada** [comment]
You cannot access the dbcontext, because it is declared behind the UnitOfWork (personally I think is useless, but this is another story).
The UnitOfWork is accessed via constructor:
```C#
public GetAllBrandsCachedQueryHandler(IUnitOfWork<int> unitOfWork, IMapper mapper, IAppCache cache)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _cache = cache;
        }
```
and declared in `src/Infrastructure/Repositories/UnitOfWork.cs`.

If you want to have access to the dbContext anywhere in your app you need to expose it via a property.
