### ISSUE TITLE
Bad Request, Header too long With Error Code 400 run using IIS Server

### ISSUE THREAD

**Issue by Beauty-Kumari** [fullstackhero/blazor-starter-kit#284]
After the completion of about 40-45 APIs, the size of the authorization token is around 40 kb. And now after login whenever any request is being sent to the server it gives error of "Bad Request, Header too long.
![Screenshot (25)](https://user-images.githubusercontent.com/58176098/130235015-049a9dca-de10-4c8b-b753-ce8c74be7f34.png)
![Screenshot (26)](https://user-images.githubusercontent.com/58176098/130235020-00e04fa5-e45e-4ae1-a9a1-8c87c1f584b1.png)

For Kestrel Server the blow code has been solved the error -
"webBuilder.ConfigureKestrel(options =>
                    {
                        options.Limits.MaxRequestHeadersTotalSize = 1048576;
                    })

But for IIS Server I haven't got any kind of solution
The solution I have tried is
1) Increased the RequestLimit from web.config file.
2) Add the MaxFieldLength and MaxRequestBytes for in
HKEY_LOCAL_MACHINE/System/CurrentControlSet/Services/HTTP/Parameters
3) Add the below code in ConfigureServices method
services.Configure<IISOptions>(options =>
            {
                options.AutomaticAuthentication = true;
                options.ForwardWindowsAuthentication = true;
            });

and many more tries but not got the final solution.
Please help if anyone can...

**Comment by iammukeshm** [comment]
Quick Question, how many permissions have you set to this user?

**Comment by Beauty-Kumari** [comment]
Around 40 to 45...

**Comment by iammukeshm** [comment]
That can be the reason for the lengthy token. Try to remove permissions and check. Currently, all permissions are stored in the token. More the permissions, the bigger the token size. Try to comment on the part where you are assigning the permission list to the token. You will need a different implementation of permission detection.

**Comment by Beauty-Kumari** [comment]
Yes, Tried to remove permissions, and the result not produce the bad request error, also not detect the permissions.
Hence, not fulfilled the requirement.
Kindly request you to suggest me any another way of permission detection implementation....

**Comment by iammukeshm** [comment]
You have 2 options

1.You need to minimize the permission constants smartly. Instead of 40*x permissions, you will need to limit it.
2.You will need to implement an API endpoint that detects the user roleId and checks internally if the user has permissions and returns a boolean.
