### ISSUE TITLE
PWA support ?

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#285]
Hi
Does anyone know if this template supports PWA? I checked to see if the manifest.js was present as well as service worker.js files and they are not? 
How would we go about adding support for PWA?
Mukesh, I emailed you on same issue, but no response ?

Many thanks
Luke

**Comment by iammukeshm** [comment]
I will try to add Pwa support in future releases or with fullstackhero once it's done.
