### ISSUE TITLE
Error No recipients have been specified - When user register

### ISSUE THREAD

**Issue by yadoy666** [fullstackhero/blazor-starter-kit#288]
**Describe the bug**
Hello, i found error when tryin register user using register form on front page 

![image](https://user-images.githubusercontent.com/6016164/130678884-c9742bd9-14a3-447e-8300-2d4d815a6e1e.png)

I dont know this bugs or i has missing something.

**Comment by iammukeshm** [comment]
@unchase  is this something related to sms?

**Comment by unchase** [comment]
Most likely this is related with MailService (MailKit.Net.Smtp)

**Comment by dcshimonek** [comment]
I was about to post the same thing. The SMTP implementation of the mail service never sets the "To" address.

**Comment by dcshimonek** [comment]
It is easy enough to work around by adding this after the initialization of the MimeMessage (line 37) in the SMPTMailService:

                email.To.Add(new MailboxAddress(request.To,request.To ));

But I think, you want a better, localizable value for the first parameter.

**Comment by yadoy666** [comment]
@dcshimonek Yes, already fix it by adding recipient to the code.

**Comment by dcshimonek** [comment]
Can you point me at that?

**Comment by dcshimonek** [comment]
This code is as broken as it was before,

**Comment by yadoy666** [comment]
@dcshimonek this error is caused like mention before. The SMTP implementation of the mail service never sets the "To" address.

**Comment by unchase** [comment]
Should add:

```csharp
email.To.Add(MailboxAddress.Parse(request.To));
```

before
https://github.com/blazorhero/CleanArchitecture/blob/45d6e675750a5138b40aa3a3c42bc89c431442a6/src/Infrastructure.Shared/Services/SMTPMailService.cs#L37
