### ISSUE TITLE
[Bug] UI totally freezes when resizing window smaller than Medium (MD)

### ISSUE THREAD

**Issue by RHaughton** [fullstackhero/blazor-starter-kit#289]
**Describe the bug**
UI Totally freezes when resizing window.

**To Reproduce**
1. Get the latest version of Blazor Hero.
2. Run it.
3. Open the Developper Console. Stretch de developper console until the MD breakpoint is hit.
4. UI Totally Freezes

**Expected behavior**
No Freezes when UI is resized

**Screenshots**
![image](https://user-images.githubusercontent.com/24850599/130803332-5283f3c1-e93d-4a26-b3de-28c86e1aad71.png)
![image](https://user-images.githubusercontent.com/24850599/130803553-817209b2-936e-42d0-a3c8-10f789554b52.png)

I Found the offending code.
When I comment Line 43 to 52 in MainLayout.razor The freezes Stops

```
 @* <MudHidden Breakpoint="Breakpoint.SmAndDown" Invert> *@
@*     <LanguageSelector/> *@
@*     <MudMenu Color="Color.Inherit" Dense Direction="Direction.Right" Icon="@Icons.Filled.Settings" OffsetY="true"> *@
@*         <div class="px-2"> *@
@*             <MudTooltip Text="@_localizer["Toggle Dark Mode"]"> *@
@*                 <MudIconButton Color="Color.Inherit" Icon="@Icons.Material.Filled.Brightness4" OnClick="@((e) => DarkMode())"/> *@
@*             </MudTooltip> *@
@*         </div> *@
@*     </MudMenu> *@
@* </MudHidden> *@
```

**Comment by RHaughton** [comment]
The issue is coming from the Tooltip on the Darkmode Icon.

This now works perfectly:

```
<MudHidden Breakpoint="Breakpoint.SmAndDown" Invert>
<LanguageSelector/>
<MudMenu Color="Color.Inherit" Dense Direction="Direction.Right" Icon="@Icons.Filled.Settings" OffsetY="true">
<div class="px-2">
  <MudIconButton Color="Color.Inherit" Icon="@Icons.Material.Filled.Brightness4" OnClick="@((e) => DarkMode())"/>
</div>
</MudMenu>
</MudHidden>
```

**Comment by iammukeshm** [comment]
Thanks for identifying the issue :)

**Comment by iammukeshm** [comment]
Added your fix in the latest code, can you check
