### ISSUE TITLE
Feature Preview Video on a more open platform?

### ISSUE THREAD

**Issue by Lutando** [fullstackhero/blazor-starter-kit#29]
**Is your feature request related to a problem? Please describe.**
Some people dont use facebook, and wont be able to access the video without an account

**Describe the solution you'd like**
Put it on a more inclusive platform like Vimeo or YouTube

**Comment by iammukeshm** [comment]
I am in the process of making a Youtube Video around the project. Will be uploaded in a couple of days.

**Comment by Lutando** [comment]
Thanks :)
