### ISSUE TITLE
Big Bug!

### ISSUE THREAD

**Issue by Amine-Smahi** [fullstackhero/blazor-starter-kit#30]
Hi, I'm just kidding.

I just want to say thank you for the amazing efforts.

Good luck!

**Comment by iammukeshm** [comment]
Haha, you got me! :D Thanks for the feedback though. Any suggestions?

Thanks

**Comment by Amine-Smahi** [comment]
I would highly suggest a good and modular file upload and display, apart from that you did a lot of work, thank you for that.
