### ISSUE TITLE
When will V3.0 be released and what is currently in development?

### ISSUE THREAD

**Issue by jeremiedevos** [fullstackhero/blazor-starter-kit#312]
Hi, 

Let me first begin with, this is a great project with fantastic features that I would love to see growing.
So, I'm wondering the following:
- Is there a way to track how things are going and what is currently being worked on?
- Is version 3.0 still in development and if so is there a release date/estimation?
- Are things still moving forward with this template because, i see that the owner is also working on other templates as well.

**Comment by iammukeshm** [comment]
Hi, as you mentioned, I am currently working on fullstackhero. BlazorHero will receive updates by November end including .NET 6. I will set up milestones in a couple of weeks.

**Comment by agorota** [comment]
Hi @iammukeshm there are news for the update to V.3.0

Thanks
