### ISSUE TITLE
AppConfiguration.Secret not working with non ASCII chars

### ISSUE THREAD

**Issue by hgdiaz** [fullstackhero/blazor-starter-kit#319]
**appsettings.json**
If you change the value of Secret under AppConfiguration and you enter non ASCII chars, the app logout users automatically.

**Example:**
  "AppConfiguration": {
    "Secret": "AdfDd%$·gtdsHGfdf"
  },

**Comment by jeremiedevos** [comment]
Maybe this documention could be of any help? 
https://docs.microsoft.com/en-us/office/troubleshoot/access/error-using-special-characters

**Comment by unchase** [comment]
Try to save json file with another encoding:

![image](https://user-images.githubusercontent.com/29679226/135241821-3a3c887f-343a-4c16-8ff4-1e3f8bd26c49.png)

![image](https://user-images.githubusercontent.com/29679226/135241697-47692dde-3a2a-45c8-88e3-5a4b30e997f6.png)

**Comment by hgdiaz** [comment]
Hi guys. I've already made a pull request with the solution.
Check PR [https://github.com/blazorhero/CleanArchitecture/pull/320](https://github.com/blazorhero/CleanArchitecture/pull/320)
