### ISSUE TITLE
UI Hangs adding/registering a new user as Admin

### ISSUE THREAD

**Issue by jaszb** [fullstackhero/blazor-starter-kit#32]
**Describe the bug**
UI Hangs when Registering a new User when logged on as admin

**To Reproduce**
1. Login using default admin account
2. Create a new User
3. Fill out dialog
4. Click Register (leaving checkboxes unchecked but makes no difference)

**Expected behavior**
User created and shown in grid

**Desktop (please complete the following information):**
 - OS: PC Win 10
 - Browser: Chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/32381192/111893292-b2f4f180-8a3c-11eb-9bfe-c851c1412c41.png)

**REQUEST DATA
![image](https://user-images.githubusercontent.com/32381192/111893496-116e9f80-8a3e-11eb-8b3c-7a4959501c70.png)

**Additional context**
`InterceptBeforeHttpAsync` is called and returns without exception or need to refresh token but the response seems to have a status_code of `BadRequest`, This status is not handled and so UI hangs.

The problem of the Response.BadRequest is the inner problem

![image](https://user-images.githubusercontent.com/32381192/111893383-5ba35100-8a3d-11eb-93be-a1f30a99ca03.png)

**Comment by iammukeshm** [comment]
Hi, the actual issue is that the username you passed it not long enough for Identity. Please try with a username longer than 6 characters.

**Comment by jaszb** [comment]
Hi @iammukeshm - for some reason the attribute was not enforced?
![image](https://user-images.githubusercontent.com/32381192/111893728-98704780-8a3f-11eb-9d27-993fd693bed8.png)

**Comment by jaszb** [comment]
Ill raise a diff separate issue...

**Comment by iammukeshm** [comment]
Yes, that was something weird. Didn't find enough time to fix it. Possible to fix and send a pull request from your side?

**Comment by 274188A** [comment]
I did some digging on this.  

`MudForm` wraps the `MudDialog` in our `RegisterUserModal.razor` page
.  
![image](https://user-images.githubusercontent.com/40014477/111927765-d5dede80-8aec-11eb-94ad-41fc050ae3fd.png)

However, when we call the `Validate` function,
![image](https://user-images.githubusercontent.com/40014477/111928112-b3999080-8aed-11eb-87ac-17b69253f248.png)

Mud only builds a **1-level-deep** list of components. It thus misses the Dialog and it's components and therefore  form.IsValid always remains true. 

I feel this is a bit of a shortcoming on the Mud library side in that there is no recursive search for components.

Not sure what your ideas are where to go from here.

**Comment by 274188A** [comment]
@iammukeshm see #33

**Comment by 274188A** [comment]
`Form.Validate()` seems to be ignoring the MinLengthAttribute.  [Required] obviously works...probably a MudBlazor bug.
The only fix I can think of for now is to add in code similar to the password field - which is a pain if you have to do this for every MinLength attribute...

**Comment by unchase** [comment]
You can try to use `StringLengthAttribute` instead of `MinLengthAttribute`.
