### ISSUE TITLE
MudForm for New User Registration does not enforce Min Length for Username

### ISSUE THREAD

**Issue by jaszb** [fullstackhero/blazor-starter-kit#33]
**Describe the bug**
New user registration allows inputs that are below min-length

**To Reproduce**
1. Add new user'

**Expected behavior**
New User added

**Actual behavior**
New User not added & UI Dialog hangs

**Comment by 274188A** [comment]
@iammukeshm - I did some digging on this.  

`MudForm` wraps the `MudDialog` in our `RegisterUserModal.razor` page
.  
![image](https://user-images.githubusercontent.com/40014477/111927765-d5dede80-8aec-11eb-94ad-41fc050ae3fd.png)

However, when we call the `Validate` function,
![image](https://user-images.githubusercontent.com/40014477/111928112-b3999080-8aed-11eb-87ac-17b69253f248.png)

Mud only builds a **1-level-deep** list of components. It thus misses the Dialog and it's components and therefore leaving `form.IsValid` in it's initial state of true. 

I feel this is a bit of a shortcoming on the Mud library side in that there is no recursive search for components.

Not sure what your ideas are where to go from here.

**Comment by iammukeshm** [comment]
I guess this is solved as well. Please check the last commit. #36
