### ISSUE TITLE
Password in json?

### ISSUE THREAD

**Issue by pawelszulik** [fullstackhero/blazor-starter-kit#35]
In file CleanArchitecture/BlazorHero.CleanArchitecture/Server/appsettings.json 
did you store valid password to ethereal.email ? :P

**Comment by iammukeshm** [comment]
Haha, yeah. It's just a test account. Nothing to secure :P My intention was to make it easy for the users to start testing the entire system without taking the trouble of configuring SMTPs.

Regards
