### ISSUE TITLE
Where is Swagger APIkey from the user?

### ISSUE THREAD

**Issue by BarehSolok** [fullstackhero/blazor-starter-kit#356]
There is no documentation so i'm lost

**Comment by jeremiedevos** [comment]
Navigate to the /catalog/products page press f12 > Fetch/XHR then press the reload button. In the developers window there is a new call to product?.... select that and the headers. The key is now in the authorization part.
![image](https://user-images.githubusercontent.com/14908622/140474451-6d92f79e-8029-4143-9888-afa5fe6aaef7.png)

**Comment by MomboMan** [comment]
Additional note. Paste the word 'Bearer', a single space then the key and nothing else.  Like this:
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aX....eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aX
with no quotes or anything.

**Comment by BarehSolok** [comment]
thanks, i just realized i can also use login api to get the token
