### ISSUE TITLE
install BlazorHero 

### ISSUE THREAD

**Issue by minhhungit** [fullstackhero/blazor-starter-kit#359]
`dotnet new --install BlazorHero.CleanArchitecture` does not install template

![image](https://user-images.githubusercontent.com/2279508/140508192-64938687-6741-4efe-a577-1c1909bd373d.png)

**Comment by iammukeshm** [comment]
I don't see a problem with it. Kindly check your network to confirm that nuget.org is not blocked for some reason.

![image](https://user-images.githubusercontent.com/31455818/140612781-c7ee7694-d4f7-4f4b-9d36-856273ef13ed.png)

**Comment by minhhungit** [comment]
@iammukeshm after disabling other nuget custom sources, it works
