### ISSUE TITLE
Modal size issue on mobile or half screen

### ISSUE THREAD

**Issue by asilmertkan** [fullstackhero/blazor-starter-kit#388]
If Modal size biggest screen do not see action buttons and do not scroll on modal (on mobile or half screen)

1. Open on mobile or Crome developer tools as a mobile 
2. Go to 'Product page'
3. Click on 'Edit Product'
4. Modal Biggest than Main screen, so you dont see Cancel or Update button

**Expected behavior**
If Modal biggest than screen modal must be with scroll

**Comment by anasseb** [comment]
Hello,
I solved this by adding this style in the MudDialog
`<MudDialog Style="height: auto; max-height: calc(100% - 20px); overflow-y: scroll">`

**Comment by asilmertkan** [comment]
Thank you, this solved my problem.
