### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by KennethB** [fullstackhero/blazor-starter-kit#389]
Need to create some code generation scripts to ensure the pattern is followed.  Consider defining the schema using Json or Yaml

**Comment by neozhu** [comment]
> Need to create some code generation scripts to ensure the pattern is followed. Consider defining the schema using Json or Yaml
Look at this
https://github.com/neozhu/CleanArchitectureCodeGenerator

**Comment by KennethB** [comment]
@neozhu thanks for the link.
