### ISSUE TITLE
Template Repository

### ISSUE THREAD

**Issue by scottkuhl** [fullstackhero/blazor-starter-kit#40]
Just a suggestion that you enable this repo to be a GitHub Template Repository under Settings.

![image](https://user-images.githubusercontent.com/4465616/112210820-2e93a180-8be9-11eb-918b-b869857eb519.png)

**Comment by iammukeshm** [comment]
Done 👍 Any suggestions/feedback regarding the Blazor Hero Project?

**Comment by scottkuhl** [comment]
> Done 👍 Any suggestions/feedback regarding the Blazor Hero Project?

You might get some good ideas here:
https://github.com/jasontaylordev/CleanArchitecture
