### ISSUE TITLE
UI Component Choice

### ISSUE THREAD

**Issue by osama9** [fullstackhero/blazor-starter-kit#42]
First, I would thank you for this template, which will be the default for my upcoming projects, but I know that I will take so much effort to replace MudBlazor with Tailwind css, 

I think by using native components will make it easier to choose what css framweork you want to use, Tailwind, bootstrap, bulma,....

**Comment by chhinsras** [comment]
You can covert the entire UI look and share

**Comment by iammukeshm** [comment]
Hi @osama9 , I would say this was more of my personal choice and how well MudBlazor and Material UI fits into the Dashboard Realm of things. However, I do understand your concern. Architecture-wise, there is almost 0 Dependency with Mudblazor Components. You are always free to switch to a new UI keeping the Core Project the same.

Regards, and thanks for the feedback.
