### ISSUE TITLE
No CQRS

### ISSUE THREAD

**Issue by JuandreG** [fullstackhero/blazor-starter-kit#421]
Hello.

How would one go about changing this project to not use the CQRS pattern. For beginners this is quite challenging to understand and with the added complexity of CQRS it makes understanding this even harder. Some guidance in this regard would be greatly appreciated.

Thanks

**Comment by matthewcorven** [comment]
@JuandreG CQRS is central to this architecture. To remove it would result in an entirely different project.

**Comment by JuandreG** [comment]
@matthewcorven Thanks for your input, I understand. Can you make any suggestions on a template I could use to learn? Maybe a DDD template that does not use CQRS?

**Comment by matthewcorven** [comment]
@JuandreG I don't believe I've ever seen a domain-driven design project that lacked CQRS.

**Comment by JuandreG** [comment]
@matthewcorven Okay thank you.
