### ISSUE TITLE
When Registering a new User

### ISSUE THREAD

**Issue by mostafaefcih** [fullstackhero/blazor-starter-kit#46]
when trying to add a new user 
if any input was invalid the page crach with 400 error
![image](https://user-images.githubusercontent.com/47594209/112747248-5cdffb00-8fb4-11eb-972e-ac0496067dcc.png)

**Comment by 274188A** [comment]
I recommend you fetch that latest code.  I tried to replicate and cannot get past the validation rule:

![image](https://user-images.githubusercontent.com/40014477/112920393-73fd2500-913b-11eb-84d5-890cfe0bc81f.png)
