### ISSUE TITLE
Allowing users to register themselves?

### ISSUE THREAD

**Issue by Duelbat** [fullstackhero/blazor-starter-kit#47]
It would be awesome if users could register themselves. Currently it appears that this template is for in-house use only, relying on an admin to add new users. This is highly impractical.

Thanks

**Comment by iammukeshm** [comment]
Yes, it will be added in the upcoming release. Already added this requirement to my to do list. Will update in a few days.

Thanks

**Comment by Duelbat** [comment]
Thanks so much Mukesh!!!
