### ISSUE TITLE
Could not update user profile

### ISSUE THREAD

**Issue by chhinsras** [fullstackhero/blazor-starter-kit#5]
**Describe the bug**
I try to update profile on : https://localhost:44398/user-profile/4f534928-1503-4972-99fa-5f4e3d7eeedd
**To Reproduce**
1. https://localhost:44398/user-profile/4f534928-1503-4972-99fa-5f4e3d7eeedd
2. Update data
3. Click save changes

**Expected behavior**
update profile

**Screenshots**
 
![image](https://user-images.githubusercontent.com/31751665/111034361-cc4bdb80-8447-11eb-8276-b255e3305197.png)

**Desktop (please complete the following information):**
Google Chrome

**Comment by iammukeshm** [comment]
Hi! This view is yet not completed. The idea is to just display profile information of other users as well. Something like a public profile page, maybe. I have not yet changed the textfields to readonly. To update the profile, one has to go to the Accounts page. The Save Changes that you see here are for Admin Only (To toggle the status of Non-Admin users). Will make it more clear in the next commit. Hold on

**Comment by iammukeshm** [comment]
Do check out the code and close this issue if necessary.
