### ISSUE TITLE
How to avoid this MAGIC string

### ISSUE THREAD

**Issue by BinSyed** [fullstackhero/blazor-starter-kit#50]
https://github.com/blazorhero/CleanArchitecture/blob/6eb901387addfcc407d5bda0564c7f0a3b39a250/BlazorHero.CleanArchitecture.Infrastructure/Services/Identity/UserService.cs#L152

**Comment by BinSyed** [comment]
@iammukeshm 
thanks for your work.

can u advise me on the above query?

thanks

**Comment by chhinsras** [comment]
You can declare as constant
