### ISSUE TITLE
Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4648, condition `<disabled>' not met

### ISSUE THREAD

**Issue by dhavalkateliya** [fullstackhero/blazor-starter-kit#51]
Hi,
first of all thanks for such a great setup to work with dotnetcore and blazor.

**Issue** : 
While running the application locally everything worked normally but when I published and deployed the **Server** project on IIS it got stuck on 1st page where MudBlazor logo is appearing. 
 
**error at console** 
`* Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4648, condition '<disabled>' not met`

**Snap :** 
![image](https://user-images.githubusercontent.com/70477147/113253663-2de2c580-92e3-11eb-80f4-5d98ae9432a6.png)
![image](https://user-images.githubusercontent.com/70477147/113253318-b319aa80-92e2-11eb-91f1-d993697c81e7.png)

It would be helpful if you can help me on this to resolve.

**Comment by iammukeshm** [comment]
I believe this is an issue at the .net level. I will check through their source and let you know. Any luck as of now?

**Comment by dhavalkateliya** [comment]
> I believe this is an issue at the .net level. I will check through their source and let you know. Any luck as of now?

I am also checking .. will update here if i find anything
thanks.

**Comment by dhavalkateliya** [comment]
Hi , i found that the issue was with versioning of mudblazor and dotnetcore components which are dependent on that

i reinstalled mudblazor with latest version and it worked .

thanks for quick reply and attention .

**Comment by iammukeshm** [comment]
I see. Thanks for letting me know. Any suggestions or feedback regarding Blazor Hero?

**Comment by dhavalkateliya** [comment]
> I see. Thanks for letting me know. Any suggestions or feedback regarding Blazor Hero?

The work you have done on this project is really great, so many useful concepts covered in single project.
Also it would be helpful if you post video regarding setting up the project and the concepts covered in this project

thanks.
