### ISSUE TITLE
Show avatar immediately after sending chat message

### ISSUE THREAD

**Issue by unchase** [fullstackhero/blazor-starter-kit#54]
**Describe the bug**
The sender's avatar does not showed after sending chat message.

**To Reproduce**
1. Authorize
2. Click on Chat
3. Choose a message receiver
4. Send a message
5. See the error

**Expected behavior**
The sender's avatar should be showed immediately after sending chat message.

**Screenshots**
![image](https://user-images.githubusercontent.com/29679226/113608309-1133ee00-9653-11eb-901b-3230f669dbf4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Browser: Yandex Browser 21.2.4.165 (64-bit)

**Comment by iammukeshm** [comment]
Hi, Are you testing with the latest code? I had noticed this issue earlier and fixed it as well. Could you pull the latest code and try it once again?

**Comment by iammukeshm** [comment]
Here's a preview.

![XGhVhV4SqW](https://user-images.githubusercontent.com/31455818/113655624-d44e1280-96b7-11eb-91d6-6d91ecd53ce5.gif)

**Comment by iammukeshm** [comment]
My bad, just understood that this bug comes up when the user image is already null. It's fixed now.
