### ISSUE TITLE
The error occured after uploading account image

### ISSUE THREAD

**Issue by unchase** [fullstackhero/blazor-starter-kit#57]
**Describe the bug**
The error occured after uploading account image.

**To Reproduce**
1. Authorize
2. Click on **Account** menu item
3. Click on **UPLOAD IMAGE** button
4. Choose the image file
5. See the error *User Not Found*

**Expected behavior**
There is no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/29679226/113758737-ef9f3900-971c-11eb-8960-3a3228c72697.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Browser: Yandex Browser 21.2.4.165 (64-bit)

**Comment by iammukeshm** [comment]
I believe it's because you have an old token that was not meant for the current user. Can you try to log out and login back, and try? I guess it should be fixed

**Comment by unchase** [comment]
I tried, does not work.
P.S. Also probably application should to logout automatically if the token has expired.

**Comment by iammukeshm** [comment]
I am not able to recreate this issue on my env. will keep you posted.
