### ISSUE TITLE
[Question] Use same port for Server and Client

### ISSUE THREAD

**Issue by RHaughton** [fullstackhero/blazor-starter-kit#58]
Hi Mukesh,

Thanks for your incredible work.
I see that in your launchsettings you use the same ip/port for server and client.

When I try to do the same I get this error: 
"Failed to bind to address https://127.0.0.1:5001: address already in use."
Am I missing something?

thanks for your help

**Comment by iammukeshm** [comment]
Hi, Client and Server are supposed to run on the same port with this ASP.NET Core Hosting Model. I guess there is another application that is already using this port. Could you try to check that or, maybe change the Blazor ports from 5001 to somethings else? It should work.

Regards

**Comment by RHaughton** [comment]
I can launch my Web API project without any issue. I can also launch my Blazor client without any issue.
I only get this error when I launch the blazor site **and** the Web Api together.

My solution is to set the Blazor site to 5003 (https) and 5002 (http) ports.
But then I need to set this line on my blazor site.
`.AddHttpClient(ClientName, client => client.BaseAddress = new Uri("https://localhost:5001/api"))`

This cause some issues :(
for example the swagger and hangfire link does'nt work.
I'm pretty sure I'm missing a setting somewhere because I cannot launch both using the same port, like you do.

**Comment by iammukeshm** [comment]
Oops. you dont have to actually run both the projects together. Just set the BlazorHero.Server project as your default startup project and run the application. The Blazor Client project will also be served in the same port. Let me know if this fixed your issue.

**Comment by iammukeshm** [comment]
And make sure both the projects are set on the same ports. You could revert back to how the ports were earlier as well.

**Comment by iammukeshm** [comment]
https://user-images.githubusercontent.com/31455818/114025365-a4a73200-9892-11eb-9dc7-6292747b99ed.mp4

Somewhat this way maybe

**Comment by RHaughton** [comment]
Thanks Mukesh I figured it out.

I didn't had a reference to the Client project from the Server project.
I still don't understand how the blazor site is detected but it works (seems a bit magic to me) but it works.

Thanks for your help!
