### ISSUE TITLE
Real time updates

### ISSUE THREAD

**Issue by codewiththomas** [fullstackhero/blazor-starter-kit#7]
Can you provide real-time updates in your project?

When two different administrators are in the product catalogue, it would be nice when the view updates automatically in the moment, the other admin adds a new product. (I guess SignalR can handle this?)

Most SignalR examples only implement a chat functionality. Would be awesome, if you could implement this.

**Comment by chhinsras** [comment]
@codewiththomas  I think Mukesh is planning for chat system with signalr

**Comment by iammukeshm** [comment]
Yes, a Real-time notifications system will be included in the v2.0 of the project along with other SignalR implementations like Chat based on Identity.

**Comment by iammukeshm** [comment]
https://user-images.githubusercontent.com/31455818/112873880-d7596980-90df-11eb-9edd-cc1ad2993477.mp4

Hi @codewiththomas , Here is a very initial implementation of the feature. Have a lot of refactoring and testings to do.

**Comment by barnybadzoo** [comment]
Looks promising so far..Great.

**Comment by iammukeshm** [comment]
https://user-images.githubusercontent.com/31455818/113031400-48665300-91ac-11eb-839c-15cde5f61380.mp4

- Real-time notification to the receiver regarding new chat messages.
- Plays Notification Tone on new message
- Scrolls to the bottom-most message
- Ability to Load Chat directly by clicking on the Notification Toast.

Any suggestions?
