### ISSUE TITLE
Settings (both server and client

### ISSUE THREAD

**Issue by iang0ld** [fullstackhero/blazor-starter-kit#70]
**Is your feature request related to a problem? Please describe.**
The one thing missing that we need is a system to store setting both application and user.

**Describe the solution you'd like**
Settings would need to be available on the server and the client for the UI (local storage?) If you are not planning this would you be able to suggest how this would best be done in Blazor?

**Describe alternatives you've considered**
Have you seen the system implemented in ASP Boilerplate?

**Comment by iammukeshm** [comment]
What kind of settings do mean?

**Comment by iammukeshm** [comment]
Currently we are storing the darkMode and the Language Preferences to the LocalStorage

**Comment by iang0ld** [comment]
It’s a pleasure to be chatting with you.

We have many settings for UI layout, feature flags etc. in our current app.  I have been waiting to reimplement is blazer with clean architecture and came across your project.  Mighty impressive!

Actually we have our own settings system in place so the examples of Dark Mode and Language should educate us on how to approach this.

**Comment by iang0ld** [comment]
This is an example of settings

https://aspnetboilerplate.com/Pages/Documents/Setting-Management#about-isettingstore

**Comment by unchase** [comment]
I added base interfaces and classes: `IPreference.cs`, `ServerPreference.cs`, `IPreferenceManager.cs`, `IServerPreferenceManager.cs`, `ServerPreferenceManager.cs`, `PreferencesController.cs` to store and interract with the settings on the server side in #69 .

It's need to be implemented `ILocalStorageService` methods in `CustomLocalStorageService.cs`

This class can be based on:
1. existing local storage
2. database
3. cache
4. configuration
5. another source
