### ISSUE TITLE
Support the use of Sqlite as database provider as alternative to Sql Server

### ISSUE THREAD

**Issue by seantrace** [fullstackhero/blazor-starter-kit#74]
**Describe the solution you'd like**
Is it possible to support Sqlite as the database provider as an alternative to Sql Server

**Comment by chhinsras** [comment]
The answer is always YES. You just need to add SQLite provider.

**Comment by nicksoftware** [comment]
Adding on @chhinsras statement,
I also had to all delete the current Migrations ,Since the migrations contained nvachar(max) which is not understood by sqlite and postgresql.
