### ISSUE TITLE
Result public bool Failed => !Succeeded; Why?

### ISSUE THREAD

**Issue by PizzaConsole** [fullstackhero/blazor-starter-kit#80]
I am just curious why this is property exists in Result... `public bool Failed => !Succeeded;` Just seems to be duplicate of `public bool Succeeded { get; set; }` especially considering the fact that it is not used at all...

![image](https://user-images.githubusercontent.com/60050783/115798436-1ac79080-a38b-11eb-9efe-d35f5b8f9053.png)

**Comment by iammukeshm** [comment]
Haha, Yes! :D This was a property added during the initial stages. If possible, could you make the changes and send in a pull request? Thanks!
