### ISSUE TITLE
Does this use wasm-like silverlight... or signal R-

### ISSUE THREAD

**Issue by swiftinitdotcom** [fullstackhero/blazor-starter-kit#81]
This is great template.
I want to know for complex makemytrip like projects will this work??
I have seen confusing info in other articles on wasm-like silverlight-does not work fast first time and also not on all browsers... or signal R- creates issues in scaling etc.
So if this is just new version of silverlight style can we use this in large web app?

i got this on first load-

**Loaded 12.36 MB resources**This application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
Now if thousands of users start hitting app, initially for all thousands of user will it be slow... this is just not good for large app where people turn away if site does not load immediately. if this is 1 mb or less may be its good for large app. may be this tech is not good at all for makemytrip type of app, only good for small internal apps. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scottkuhl** [comment]
WASM is really nothing like Silverlight.  Silverlight was a browser plugin and Blazor is using Web Assembly which is a standard browser feature.

It seems like what you are really concerned about is the initial download and load time.  Is that correct?

If so, I have two comments on that topic.

1 - Is this is a web application, something a user will use more like an application? Then Blazor Web Assembly out of the box works pretty well on desktop and mobile as long as the user is on a modern browser.  You can put up a landing page that is not Blazor just to have a nice splash screen telling about the site with some sort of a launch web app link or button if the application gets too large.  Microsoft is making big strides in the download and performance area so this will only get better with time,

2 - Is this a web site you want Google to index and feel less like an app?  Then you should look into pre-rendering.  That will help a lot and more support for that is coming in .NET 6.
