### ISSUE TITLE
Upload Image to user craches app

### ISSUE THREAD

**Issue by inginheiiro** [fullstackhero/blazor-starter-kit#86]
**Describe the bug**
The project/solution Crashes When i try to upload a image to the profile

**To Reproduce**
1. Go to 'Accounts'
2. Click on 'Upload Image'

**Expected behavior**
The image is uploaded if we restart the solution (RUN) but crashes on the process

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version latest

**Comment by iammukeshm** [comment]
Can you verify if the directory of the blazor application is not write protected?

**Comment by inginheiiro** [comment]
https://user-images.githubusercontent.com/19993596/116515160-d6288180-a8c3-11eb-95b0-6776be979066.mp4

I'm running VS as Admin. I haven´t get the chance to debug, i can help you on the weekend probably...
I't seems like a bug, please check the video.

best

**Comment by iammukeshm** [comment]
Could you check what is the exact error message you get in the browser console - developer tools?
Also, please try to logout and login again, there might be an issue of the expired or not available user. Try this first.

**Comment by inginheiiro** [comment]
Hi,
Logout->login with full admin user.
Tried to upload an image.


![image](https://user-images.githubusercontent.com/19993596/116525372-5b199800-a8d0-11eb-960f-eb280c743228.png)

**Comment by iammukeshm** [comment]
I am really not sure of this issue. No one else have reported this. I tested it right now. Seems fine for me. Maybe try to update your mudblazor package in the project.


https://user-images.githubusercontent.com/31455818/116526521-4ef50100-a8f7-11eb-904e-4bf230a267d0.mp4

**Comment by inginheiiro** [comment]
Yes, i've updated 3 packages, including mudblazor.

hum... so it could be and mudblazor issue?

i will try to downgrade.

thanks

**Comment by iammukeshm** [comment]
I cannot say that it is a mudblazor issue, as it actually works for me. But mud components show up as errors in your console. Not very sure.
Please try to run the application on different browsers without caching it.
Also, you could try to clone this repository instead of using the nugget package, to check if it works. Let me know.

**Comment by inginheiiro** [comment]
I've cloned the repo and run it and still crashes. I did not update anything.

![image](https://user-images.githubusercontent.com/19993596/116612603-a6af5e80-a92f-11eb-84d1-a29dc773403d.png)

I've never used blazor+webassembly and i'm not able to debug...

Using framework 5.0.4
