### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by iang0ld** [fullstackhero/blazor-starter-kit#88]
Are there any plans to add unit Test project

**Comment by iammukeshm** [comment]
Yes, but it will take some time as I am caught up on other things as well. But test projects will definitely be a part of the project,

**Comment by scottkuhl** [comment]
Should this be re-opened as an issue to track?  I almost opened a new issue on testing and found this old closed one.  Right now it does not appear on the V3 roadmap.

_Modular Architecture
Cleaner Separation Of Code
Dedicated Documentation Website - Here
Tutorials to add new entities, controllers
UI Updates
Support for PostgreSQL / MySQL - Easy DB Switching
Theme Manager Integration to change UI Color Palletes / Fonts on the go.
You can suggest your requirements as well!_
