### ISSUE TITLE
Multi-Tenancy

### ISSUE THREAD

**Issue by sahvey** [fullstackhero/blazor-starter-kit#9]
Multi-Tenancy is a widely used architecture to create SaaS applications where the hardware and software resources are shared by the customers (tenants). 
It will be great if this feature is added.

**Comment by chhinsras** [comment]
There are three options for multi tenant:
1. Single App Single DB
2. Multiple App Single DB
3. Single App Multiple DB

**Comment by sahvey** [comment]
Should be able to support all three options.

**Comment by iammukeshm** [comment]
Will add this feature later down the roadmap. This was not one of the things I had initially in my mind while planning this project. But yes, will be adding it over time.
