### ISSUE TITLE
MultiTenancy

### ISSUE THREAD

**Issue by pointlevel** [fullstackhero/blazor-starter-kit#92]
Great template :)

Would be awesome if this template also includes the ability to use it with multitenacy.

**Comment by iammukeshm** [comment]
Thanks.
I will be adding MultiTenancy in the upcoming versions. It would be great if you could point me to some good articles/ projects that demonstrate multitenancy. Regards

**Comment by pointlevel** [comment]
Hi!

I think that you get a lot of inspiration from the framework [abp.io](https://abp.io) or [aspnetboilerplate.com](https://aspnetboilerplate.com)
(Its good frameworks overall, but way to complicated for many needs)

**Comment by pointlevel** [comment]
Maybe this could be a good thing to implement: https://github.com/CodEaisy/TinySaas
