### ISSUE TITLE
The MudTextField`1 field is required. appears as validation message 

### ISSUE THREAD

**Issue by kulcsar** [fullstackhero/blazor-starter-kit#95]
**Describe the bug**
When trying to create a new Brand item with empty Name\Description the UI displays the The MudTextField`1 field is required. instead of Name is required, Description is required. The same happens on Product, User, etc pages.

**To Reproduce**
1. Go to 'Brands'
2. Click on 'Create'
3. Click into 'Description'
4. See the wrong validation Message.

**Expected behavior**
Name is required, Description is required should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/17300976/116825541-1459c580-ab90-11eb-9c8d-f1d653d374b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by amitpercept** [comment]
In AddEditBrandModal.razor file place ErrorText in MudTextField as mentioned below:

<MudTextField T="string" For="@(() => Name)" @bind-Value="Name" Required="true" Label="@localizer["Name"]" **ErrorText="Brand is required!"**/>

You can specify desired Error message in other fields as well like above.

**Comment by unchase** [comment]
> In AddEditBrandModal.razor file place ErrorText in MudTextField as mentioned below:
> 
> <MudTextField T="string" For="@(() => Name)" @bind-Value="Name" Required="true" Label="@localizer["Name"]" **ErrorText="Brand is required!"**/>
> 
> You can specify desired Error message in other fields as well like above.

This only works for Required fields, it will not work for other validation attributes.
