### ISSUE TITLE
Failed update database or manage migration using CLI

### ISSUE THREAD

**Issue by rioda78** [fullstackhero/blazor-starter-kit#96]
failed update database or manage migration using CLI

**To Reproduce**
1. follow quick start guide to create new project
2. update database using CLI with command "dotnet ef database update"
error message "unable to create object of type "BlazorHeroContext". for different patterns supported at design time , see  https://go.microsoft.com/fwlink/?linkid=851728"

**Expected behavior**
im expected this running well like using Package manage console (PMC) with command : "update-database"

**Desktop (please complete the following information):**
 - OS: Windows 64
 - Sql server : 2008 R2
 - Net Core : 5

**Comment by tympaniplayer** [comment]
@iammukeshm is this closed because only Visual Studio 2019 is supported and not `dotnet ef database update`? I was hoping to do my development on linux instead of windows if possible
