### ISSUE TITLE
Sortin not working on Products

### ISSUE THREAD

**Issue by Eodar** [fullstackhero/blazor-starter-kit#97]
**Describe the bug**
Sorting is not working on Products. When clickin on arrow nothing happens 

**To Reproduce**
1. Go to  catalog/products
2. Click on Arrow 🠓

**Expected behavior**
Table should sort  by alphabetical values 

**Screenshots**

![obraz](https://user-images.githubusercontent.com/29659679/117303925-81fe3e00-ae7d-11eb-882b-1a8d2a8b3354.png)
![obraz](https://user-images.githubusercontent.com/29659679/117303974-8c203c80-ae7d-11eb-8d7d-ab991e7494c2.png)
![obraz](https://user-images.githubusercontent.com/29659679/117304240-d2759b80-ae7d-11eb-852e-f03b49a70573.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 88.0.1 (64 bity)

**Comment by unchase** [comment]
Hi, @Eodar 
Try to update to the lastest version:

![sort](https://user-images.githubusercontent.com/29679226/117455505-eab5eb00-af4f-11eb-9ae0-11c29e0c328c.gif)
