### ISSUE TITLE
Add migrations in code

### ISSUE THREAD

**Issue by cmorgado** [fullstackhero/blazor-starter-kit#98]
Instead of running a command line to install/upgrade the DB ... why not do it in code

I just did it with some lines of code in the program.cs

 public static async Task Main(string[] args)

       {
  
          var host = CreateHostBuilder(args).Build();
      
      using (var scope = host.Services.CreateScope())
   
         {
                var services = scope.ServiceProvider;

                var context = services.GetRequiredService<BlazorHeroContext>();

                try
                {

                    if (context.Database.IsSqlServer())

                    {
 
                       await context.Database.MigrateAsync();

                    }

                }
                catch (Exception ex)
                {

                    Log.Error(ex, "An error occurred while migrating database.");

                    throw;
 
               }

            }

           host.Run();
 
       }

**Comment by iammukeshm** [comment]
Initially, I have implemented this as well. But EF acts weird at times, and it's not a good idea to Migrate every time the application starts up. Can cause a clash with existing DB schema. This is what I had noticed. Thus, removed the auto migrate code.
